// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blockchain.proto

package types

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TxType int32

const (
	TxType_NORMAL     TxType = 0
	TxType_GOVERNANCE TxType = 1
	TxType_REDEPLOY   TxType = 2
)

var TxType_name = map[int32]string{
	0: "NORMAL",
	1: "GOVERNANCE",
	2: "REDEPLOY",
}

var TxType_value = map[string]int32{
	"NORMAL":     0,
	"GOVERNANCE": 1,
	"REDEPLOY":   2,
}

func (x TxType) String() string {
	return proto.EnumName(TxType_name, int32(x))
}

func (TxType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e9ac6287ce250c9a, []int{0}
}

type Block struct {
	Hash                 []byte       `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Header               *BlockHeader `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	Body                 *BlockBody   `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ac6287ce250c9a, []int{0}
}
func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Block) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *Block) GetBody() *BlockBody {
	if m != nil {
		return m.Body
	}
	return nil
}

type BlockHeader struct {
	ChainID              []byte   `protobuf:"bytes,1,opt,name=chainID,proto3" json:"chainID,omitempty"`
	PrevBlockHash        []byte   `protobuf:"bytes,2,opt,name=prevBlockHash,proto3" json:"prevBlockHash,omitempty"`
	BlockNo              uint64   `protobuf:"varint,3,opt,name=blockNo,proto3" json:"blockNo,omitempty"`
	Timestamp            int64    `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	BlocksRootHash       []byte   `protobuf:"bytes,5,opt,name=blocksRootHash,proto3" json:"blocksRootHash,omitempty"`
	TxsRootHash          []byte   `protobuf:"bytes,6,opt,name=txsRootHash,proto3" json:"txsRootHash,omitempty"`
	ReceiptsRootHash     []byte   `protobuf:"bytes,7,opt,name=receiptsRootHash,proto3" json:"receiptsRootHash,omitempty"`
	Confirms             uint64   `protobuf:"varint,8,opt,name=confirms,proto3" json:"confirms,omitempty"`
	PubKey               []byte   `protobuf:"bytes,9,opt,name=pubKey,proto3" json:"pubKey,omitempty"`
	CoinbaseAccount      []byte   `protobuf:"bytes,10,opt,name=coinbaseAccount,proto3" json:"coinbaseAccount,omitempty"`
	Sign                 []byte   `protobuf:"bytes,11,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockHeader) Reset()         { *m = BlockHeader{} }
func (m *BlockHeader) String() string { return proto.CompactTextString(m) }
func (*BlockHeader) ProtoMessage()    {}
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ac6287ce250c9a, []int{1}
}
func (m *BlockHeader) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeader.Unmarshal(m, b)
}
func (m *BlockHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeader.Marshal(b, m, deterministic)
}
func (m *BlockHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeader.Merge(m, src)
}
func (m *BlockHeader) XXX_Size() int {
	return xxx_messageInfo_BlockHeader.Size(m)
}
func (m *BlockHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeader.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeader proto.InternalMessageInfo

func (m *BlockHeader) GetChainID() []byte {
	if m != nil {
		return m.ChainID
	}
	return nil
}

func (m *BlockHeader) GetPrevBlockHash() []byte {
	if m != nil {
		return m.PrevBlockHash
	}
	return nil
}

func (m *BlockHeader) GetBlockNo() uint64 {
	if m != nil {
		return m.BlockNo
	}
	return 0
}

func (m *BlockHeader) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *BlockHeader) GetBlocksRootHash() []byte {
	if m != nil {
		return m.BlocksRootHash
	}
	return nil
}

func (m *BlockHeader) GetTxsRootHash() []byte {
	if m != nil {
		return m.TxsRootHash
	}
	return nil
}

func (m *BlockHeader) GetReceiptsRootHash() []byte {
	if m != nil {
		return m.ReceiptsRootHash
	}
	return nil
}

func (m *BlockHeader) GetConfirms() uint64 {
	if m != nil {
		return m.Confirms
	}
	return 0
}

func (m *BlockHeader) GetPubKey() []byte {
	if m != nil {
		return m.PubKey
	}
	return nil
}

func (m *BlockHeader) GetCoinbaseAccount() []byte {
	if m != nil {
		return m.CoinbaseAccount
	}
	return nil
}

func (m *BlockHeader) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

type BlockBody struct {
	Txs                  []*Tx    `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockBody) Reset()         { *m = BlockBody{} }
func (m *BlockBody) String() string { return proto.CompactTextString(m) }
func (*BlockBody) ProtoMessage()    {}
func (*BlockBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ac6287ce250c9a, []int{2}
}
func (m *BlockBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockBody.Unmarshal(m, b)
}
func (m *BlockBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockBody.Marshal(b, m, deterministic)
}
func (m *BlockBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockBody.Merge(m, src)
}
func (m *BlockBody) XXX_Size() int {
	return xxx_messageInfo_BlockBody.Size(m)
}
func (m *BlockBody) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockBody.DiscardUnknown(m)
}

var xxx_messageInfo_BlockBody proto.InternalMessageInfo

func (m *BlockBody) GetTxs() []*Tx {
	if m != nil {
		return m.Txs
	}
	return nil
}

type TxList struct {
	Txs                  []*Tx    `protobuf:"bytes,1,rep,name=txs,proto3" json:"txs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxList) Reset()         { *m = TxList{} }
func (m *TxList) String() string { return proto.CompactTextString(m) }
func (*TxList) ProtoMessage()    {}
func (*TxList) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ac6287ce250c9a, []int{3}
}
func (m *TxList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxList.Unmarshal(m, b)
}
func (m *TxList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxList.Marshal(b, m, deterministic)
}
func (m *TxList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxList.Merge(m, src)
}
func (m *TxList) XXX_Size() int {
	return xxx_messageInfo_TxList.Size(m)
}
func (m *TxList) XXX_DiscardUnknown() {
	xxx_messageInfo_TxList.DiscardUnknown(m)
}

var xxx_messageInfo_TxList proto.InternalMessageInfo

func (m *TxList) GetTxs() []*Tx {
	if m != nil {
		return m.Txs
	}
	return nil
}

type Tx struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Body                 *TxBody  `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tx) Reset()         { *m = Tx{} }
func (m *Tx) String() string { return proto.CompactTextString(m) }
func (*Tx) ProtoMessage()    {}
func (*Tx) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ac6287ce250c9a, []int{4}
}
func (m *Tx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tx.Unmarshal(m, b)
}
func (m *Tx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tx.Marshal(b, m, deterministic)
}
func (m *Tx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tx.Merge(m, src)
}
func (m *Tx) XXX_Size() int {
	return xxx_messageInfo_Tx.Size(m)
}
func (m *Tx) XXX_DiscardUnknown() {
	xxx_messageInfo_Tx.DiscardUnknown(m)
}

var xxx_messageInfo_Tx proto.InternalMessageInfo

func (m *Tx) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Tx) GetBody() *TxBody {
	if m != nil {
		return m.Body
	}
	return nil
}

type TxBody struct {
	Nonce                uint64   `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Account              []byte   `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	Recipient            []byte   `protobuf:"bytes,3,opt,name=recipient,proto3" json:"recipient,omitempty"`
	Amount               []byte   `protobuf:"bytes,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Payload              []byte   `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	GasLimit             uint64   `protobuf:"varint,6,opt,name=gasLimit,proto3" json:"gasLimit,omitempty"`
	GasPrice             []byte   `protobuf:"bytes,7,opt,name=gasPrice,proto3" json:"gasPrice,omitempty"`
	Type                 TxType   `protobuf:"varint,8,opt,name=type,proto3,enum=types.TxType" json:"type,omitempty"`
	ChainIdHash          []byte   `protobuf:"bytes,9,opt,name=chainIdHash,proto3" json:"chainIdHash,omitempty"`
	Sign                 []byte   `protobuf:"bytes,10,opt,name=sign,proto3" json:"sign,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxBody) Reset()         { *m = TxBody{} }
func (m *TxBody) String() string { return proto.CompactTextString(m) }
func (*TxBody) ProtoMessage()    {}
func (*TxBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ac6287ce250c9a, []int{5}
}
func (m *TxBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxBody.Unmarshal(m, b)
}
func (m *TxBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxBody.Marshal(b, m, deterministic)
}
func (m *TxBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxBody.Merge(m, src)
}
func (m *TxBody) XXX_Size() int {
	return xxx_messageInfo_TxBody.Size(m)
}
func (m *TxBody) XXX_DiscardUnknown() {
	xxx_messageInfo_TxBody.DiscardUnknown(m)
}

var xxx_messageInfo_TxBody proto.InternalMessageInfo

func (m *TxBody) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *TxBody) GetAccount() []byte {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *TxBody) GetRecipient() []byte {
	if m != nil {
		return m.Recipient
	}
	return nil
}

func (m *TxBody) GetAmount() []byte {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *TxBody) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *TxBody) GetGasLimit() uint64 {
	if m != nil {
		return m.GasLimit
	}
	return 0
}

func (m *TxBody) GetGasPrice() []byte {
	if m != nil {
		return m.GasPrice
	}
	return nil
}

func (m *TxBody) GetType() TxType {
	if m != nil {
		return m.Type
	}
	return TxType_NORMAL
}

func (m *TxBody) GetChainIdHash() []byte {
	if m != nil {
		return m.ChainIdHash
	}
	return nil
}

func (m *TxBody) GetSign() []byte {
	if m != nil {
		return m.Sign
	}
	return nil
}

// TxIdx specifies a transaction's block hash and index within the block body
type TxIdx struct {
	BlockHash            []byte   `protobuf:"bytes,1,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	Idx                  int32    `protobuf:"varint,2,opt,name=idx,proto3" json:"idx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxIdx) Reset()         { *m = TxIdx{} }
func (m *TxIdx) String() string { return proto.CompactTextString(m) }
func (*TxIdx) ProtoMessage()    {}
func (*TxIdx) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ac6287ce250c9a, []int{6}
}
func (m *TxIdx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxIdx.Unmarshal(m, b)
}
func (m *TxIdx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxIdx.Marshal(b, m, deterministic)
}
func (m *TxIdx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxIdx.Merge(m, src)
}
func (m *TxIdx) XXX_Size() int {
	return xxx_messageInfo_TxIdx.Size(m)
}
func (m *TxIdx) XXX_DiscardUnknown() {
	xxx_messageInfo_TxIdx.DiscardUnknown(m)
}

var xxx_messageInfo_TxIdx proto.InternalMessageInfo

func (m *TxIdx) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

func (m *TxIdx) GetIdx() int32 {
	if m != nil {
		return m.Idx
	}
	return 0
}

type TxInBlock struct {
	TxIdx                *TxIdx   `protobuf:"bytes,1,opt,name=txIdx,proto3" json:"txIdx,omitempty"`
	Tx                   *Tx      `protobuf:"bytes,2,opt,name=tx,proto3" json:"tx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TxInBlock) Reset()         { *m = TxInBlock{} }
func (m *TxInBlock) String() string { return proto.CompactTextString(m) }
func (*TxInBlock) ProtoMessage()    {}
func (*TxInBlock) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ac6287ce250c9a, []int{7}
}
func (m *TxInBlock) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxInBlock.Unmarshal(m, b)
}
func (m *TxInBlock) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxInBlock.Marshal(b, m, deterministic)
}
func (m *TxInBlock) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxInBlock.Merge(m, src)
}
func (m *TxInBlock) XXX_Size() int {
	return xxx_messageInfo_TxInBlock.Size(m)
}
func (m *TxInBlock) XXX_DiscardUnknown() {
	xxx_messageInfo_TxInBlock.DiscardUnknown(m)
}

var xxx_messageInfo_TxInBlock proto.InternalMessageInfo

func (m *TxInBlock) GetTxIdx() *TxIdx {
	if m != nil {
		return m.TxIdx
	}
	return nil
}

func (m *TxInBlock) GetTx() *Tx {
	if m != nil {
		return m.Tx
	}
	return nil
}

type State struct {
	Nonce                uint64   `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Balance              []byte   `protobuf:"bytes,2,opt,name=balance,proto3" json:"balance,omitempty"`
	CodeHash             []byte   `protobuf:"bytes,3,opt,name=codeHash,proto3" json:"codeHash,omitempty"`
	StorageRoot          []byte   `protobuf:"bytes,4,opt,name=storageRoot,proto3" json:"storageRoot,omitempty"`
	SqlRecoveryPoint     uint64   `protobuf:"varint,5,opt,name=sqlRecoveryPoint,proto3" json:"sqlRecoveryPoint,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *State) Reset()         { *m = State{} }
func (m *State) String() string { return proto.CompactTextString(m) }
func (*State) ProtoMessage()    {}
func (*State) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ac6287ce250c9a, []int{8}
}
func (m *State) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_State.Unmarshal(m, b)
}
func (m *State) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_State.Marshal(b, m, deterministic)
}
func (m *State) XXX_Merge(src proto.Message) {
	xxx_messageInfo_State.Merge(m, src)
}
func (m *State) XXX_Size() int {
	return xxx_messageInfo_State.Size(m)
}
func (m *State) XXX_DiscardUnknown() {
	xxx_messageInfo_State.DiscardUnknown(m)
}

var xxx_messageInfo_State proto.InternalMessageInfo

func (m *State) GetNonce() uint64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

func (m *State) GetBalance() []byte {
	if m != nil {
		return m.Balance
	}
	return nil
}

func (m *State) GetCodeHash() []byte {
	if m != nil {
		return m.CodeHash
	}
	return nil
}

func (m *State) GetStorageRoot() []byte {
	if m != nil {
		return m.StorageRoot
	}
	return nil
}

func (m *State) GetSqlRecoveryPoint() uint64 {
	if m != nil {
		return m.SqlRecoveryPoint
	}
	return 0
}

type AccountProof struct {
	State                *State   `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Inclusion            bool     `protobuf:"varint,2,opt,name=inclusion,proto3" json:"inclusion,omitempty"`
	Key                  []byte   `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	ProofKey             []byte   `protobuf:"bytes,4,opt,name=proofKey,proto3" json:"proofKey,omitempty"`
	ProofVal             []byte   `protobuf:"bytes,5,opt,name=proofVal,proto3" json:"proofVal,omitempty"`
	Bitmap               []byte   `protobuf:"bytes,6,opt,name=bitmap,proto3" json:"bitmap,omitempty"`
	Height               uint32   `protobuf:"varint,7,opt,name=height,proto3" json:"height,omitempty"`
	AuditPath            [][]byte `protobuf:"bytes,8,rep,name=auditPath,proto3" json:"auditPath,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountProof) Reset()         { *m = AccountProof{} }
func (m *AccountProof) String() string { return proto.CompactTextString(m) }
func (*AccountProof) ProtoMessage()    {}
func (*AccountProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ac6287ce250c9a, []int{9}
}
func (m *AccountProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountProof.Unmarshal(m, b)
}
func (m *AccountProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountProof.Marshal(b, m, deterministic)
}
func (m *AccountProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountProof.Merge(m, src)
}
func (m *AccountProof) XXX_Size() int {
	return xxx_messageInfo_AccountProof.Size(m)
}
func (m *AccountProof) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountProof.DiscardUnknown(m)
}

var xxx_messageInfo_AccountProof proto.InternalMessageInfo

func (m *AccountProof) GetState() *State {
	if m != nil {
		return m.State
	}
	return nil
}

func (m *AccountProof) GetInclusion() bool {
	if m != nil {
		return m.Inclusion
	}
	return false
}

func (m *AccountProof) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *AccountProof) GetProofKey() []byte {
	if m != nil {
		return m.ProofKey
	}
	return nil
}

func (m *AccountProof) GetProofVal() []byte {
	if m != nil {
		return m.ProofVal
	}
	return nil
}

func (m *AccountProof) GetBitmap() []byte {
	if m != nil {
		return m.Bitmap
	}
	return nil
}

func (m *AccountProof) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *AccountProof) GetAuditPath() [][]byte {
	if m != nil {
		return m.AuditPath
	}
	return nil
}

type ContractVarProof struct {
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Inclusion            bool     `protobuf:"varint,2,opt,name=inclusion,proto3" json:"inclusion,omitempty"`
	ProofKey             []byte   `protobuf:"bytes,4,opt,name=proofKey,proto3" json:"proofKey,omitempty"`
	ProofVal             []byte   `protobuf:"bytes,5,opt,name=proofVal,proto3" json:"proofVal,omitempty"`
	Bitmap               []byte   `protobuf:"bytes,6,opt,name=bitmap,proto3" json:"bitmap,omitempty"`
	Height               uint32   `protobuf:"varint,7,opt,name=height,proto3" json:"height,omitempty"`
	AuditPath            [][]byte `protobuf:"bytes,8,rep,name=auditPath,proto3" json:"auditPath,omitempty"`
	Key                  []byte   `protobuf:"bytes,9,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ContractVarProof) Reset()         { *m = ContractVarProof{} }
func (m *ContractVarProof) String() string { return proto.CompactTextString(m) }
func (*ContractVarProof) ProtoMessage()    {}
func (*ContractVarProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ac6287ce250c9a, []int{10}
}
func (m *ContractVarProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContractVarProof.Unmarshal(m, b)
}
func (m *ContractVarProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContractVarProof.Marshal(b, m, deterministic)
}
func (m *ContractVarProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContractVarProof.Merge(m, src)
}
func (m *ContractVarProof) XXX_Size() int {
	return xxx_messageInfo_ContractVarProof.Size(m)
}
func (m *ContractVarProof) XXX_DiscardUnknown() {
	xxx_messageInfo_ContractVarProof.DiscardUnknown(m)
}

var xxx_messageInfo_ContractVarProof proto.InternalMessageInfo

func (m *ContractVarProof) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ContractVarProof) GetInclusion() bool {
	if m != nil {
		return m.Inclusion
	}
	return false
}

func (m *ContractVarProof) GetProofKey() []byte {
	if m != nil {
		return m.ProofKey
	}
	return nil
}

func (m *ContractVarProof) GetProofVal() []byte {
	if m != nil {
		return m.ProofVal
	}
	return nil
}

func (m *ContractVarProof) GetBitmap() []byte {
	if m != nil {
		return m.Bitmap
	}
	return nil
}

func (m *ContractVarProof) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *ContractVarProof) GetAuditPath() [][]byte {
	if m != nil {
		return m.AuditPath
	}
	return nil
}

func (m *ContractVarProof) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type StateQueryProof struct {
	ContractProof        *AccountProof       `protobuf:"bytes,1,opt,name=contractProof,proto3" json:"contractProof,omitempty"`
	VarProofs            []*ContractVarProof `protobuf:"bytes,2,rep,name=varProofs,proto3" json:"varProofs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *StateQueryProof) Reset()         { *m = StateQueryProof{} }
func (m *StateQueryProof) String() string { return proto.CompactTextString(m) }
func (*StateQueryProof) ProtoMessage()    {}
func (*StateQueryProof) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ac6287ce250c9a, []int{11}
}
func (m *StateQueryProof) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateQueryProof.Unmarshal(m, b)
}
func (m *StateQueryProof) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateQueryProof.Marshal(b, m, deterministic)
}
func (m *StateQueryProof) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateQueryProof.Merge(m, src)
}
func (m *StateQueryProof) XXX_Size() int {
	return xxx_messageInfo_StateQueryProof.Size(m)
}
func (m *StateQueryProof) XXX_DiscardUnknown() {
	xxx_messageInfo_StateQueryProof.DiscardUnknown(m)
}

var xxx_messageInfo_StateQueryProof proto.InternalMessageInfo

func (m *StateQueryProof) GetContractProof() *AccountProof {
	if m != nil {
		return m.ContractProof
	}
	return nil
}

func (m *StateQueryProof) GetVarProofs() []*ContractVarProof {
	if m != nil {
		return m.VarProofs
	}
	return nil
}

type Receipt struct {
	ContractAddress      []byte   `protobuf:"bytes,1,opt,name=contractAddress,proto3" json:"contractAddress,omitempty"`
	Status               string   `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Ret                  string   `protobuf:"bytes,3,opt,name=ret,proto3" json:"ret,omitempty"`
	TxHash               []byte   `protobuf:"bytes,4,opt,name=txHash,proto3" json:"txHash,omitempty"`
	FeeUsed              []byte   `protobuf:"bytes,5,opt,name=feeUsed,proto3" json:"feeUsed,omitempty"`
	CumulativeFeeUsed    []byte   `protobuf:"bytes,6,opt,name=cumulativeFeeUsed,proto3" json:"cumulativeFeeUsed,omitempty"`
	Bloom                []byte   `protobuf:"bytes,7,opt,name=bloom,proto3" json:"bloom,omitempty"`
	Events               []*Event `protobuf:"bytes,8,rep,name=events,proto3" json:"events,omitempty"`
	BlockNo              uint64   `protobuf:"varint,9,opt,name=blockNo,proto3" json:"blockNo,omitempty"`
	BlockHash            []byte   `protobuf:"bytes,10,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	TxIndex              int32    `protobuf:"varint,11,opt,name=txIndex,proto3" json:"txIndex,omitempty"`
	From                 []byte   `protobuf:"bytes,12,opt,name=from,proto3" json:"from,omitempty"`
	To                   []byte   `protobuf:"bytes,13,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Receipt) Reset()         { *m = Receipt{} }
func (m *Receipt) String() string { return proto.CompactTextString(m) }
func (*Receipt) ProtoMessage()    {}
func (*Receipt) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ac6287ce250c9a, []int{12}
}
func (m *Receipt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Receipt.Unmarshal(m, b)
}
func (m *Receipt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Receipt.Marshal(b, m, deterministic)
}
func (m *Receipt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Receipt.Merge(m, src)
}
func (m *Receipt) XXX_Size() int {
	return xxx_messageInfo_Receipt.Size(m)
}
func (m *Receipt) XXX_DiscardUnknown() {
	xxx_messageInfo_Receipt.DiscardUnknown(m)
}

var xxx_messageInfo_Receipt proto.InternalMessageInfo

func (m *Receipt) GetContractAddress() []byte {
	if m != nil {
		return m.ContractAddress
	}
	return nil
}

func (m *Receipt) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Receipt) GetRet() string {
	if m != nil {
		return m.Ret
	}
	return ""
}

func (m *Receipt) GetTxHash() []byte {
	if m != nil {
		return m.TxHash
	}
	return nil
}

func (m *Receipt) GetFeeUsed() []byte {
	if m != nil {
		return m.FeeUsed
	}
	return nil
}

func (m *Receipt) GetCumulativeFeeUsed() []byte {
	if m != nil {
		return m.CumulativeFeeUsed
	}
	return nil
}

func (m *Receipt) GetBloom() []byte {
	if m != nil {
		return m.Bloom
	}
	return nil
}

func (m *Receipt) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *Receipt) GetBlockNo() uint64 {
	if m != nil {
		return m.BlockNo
	}
	return 0
}

func (m *Receipt) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

func (m *Receipt) GetTxIndex() int32 {
	if m != nil {
		return m.TxIndex
	}
	return 0
}

func (m *Receipt) GetFrom() []byte {
	if m != nil {
		return m.From
	}
	return nil
}

func (m *Receipt) GetTo() []byte {
	if m != nil {
		return m.To
	}
	return nil
}

type Event struct {
	ContractAddress      []byte   `protobuf:"bytes,1,opt,name=contractAddress,proto3" json:"contractAddress,omitempty"`
	EventName            string   `protobuf:"bytes,2,opt,name=eventName,proto3" json:"eventName,omitempty"`
	JsonArgs             string   `protobuf:"bytes,3,opt,name=jsonArgs,proto3" json:"jsonArgs,omitempty"`
	EventIdx             int32    `protobuf:"varint,4,opt,name=eventIdx,proto3" json:"eventIdx,omitempty"`
	TxHash               []byte   `protobuf:"bytes,5,opt,name=txHash,proto3" json:"txHash,omitempty"`
	BlockHash            []byte   `protobuf:"bytes,6,opt,name=blockHash,proto3" json:"blockHash,omitempty"`
	BlockNo              uint64   `protobuf:"varint,7,opt,name=blockNo,proto3" json:"blockNo,omitempty"`
	TxIndex              int32    `protobuf:"varint,8,opt,name=txIndex,proto3" json:"txIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ac6287ce250c9a, []int{13}
}
func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetContractAddress() []byte {
	if m != nil {
		return m.ContractAddress
	}
	return nil
}

func (m *Event) GetEventName() string {
	if m != nil {
		return m.EventName
	}
	return ""
}

func (m *Event) GetJsonArgs() string {
	if m != nil {
		return m.JsonArgs
	}
	return ""
}

func (m *Event) GetEventIdx() int32 {
	if m != nil {
		return m.EventIdx
	}
	return 0
}

func (m *Event) GetTxHash() []byte {
	if m != nil {
		return m.TxHash
	}
	return nil
}

func (m *Event) GetBlockHash() []byte {
	if m != nil {
		return m.BlockHash
	}
	return nil
}

func (m *Event) GetBlockNo() uint64 {
	if m != nil {
		return m.BlockNo
	}
	return 0
}

func (m *Event) GetTxIndex() int32 {
	if m != nil {
		return m.TxIndex
	}
	return 0
}

type FnArgument struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FnArgument) Reset()         { *m = FnArgument{} }
func (m *FnArgument) String() string { return proto.CompactTextString(m) }
func (*FnArgument) ProtoMessage()    {}
func (*FnArgument) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ac6287ce250c9a, []int{14}
}
func (m *FnArgument) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FnArgument.Unmarshal(m, b)
}
func (m *FnArgument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FnArgument.Marshal(b, m, deterministic)
}
func (m *FnArgument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FnArgument.Merge(m, src)
}
func (m *FnArgument) XXX_Size() int {
	return xxx_messageInfo_FnArgument.Size(m)
}
func (m *FnArgument) XXX_DiscardUnknown() {
	xxx_messageInfo_FnArgument.DiscardUnknown(m)
}

var xxx_messageInfo_FnArgument proto.InternalMessageInfo

func (m *FnArgument) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Function struct {
	Name                 string        `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Arguments            []*FnArgument `protobuf:"bytes,2,rep,name=arguments,proto3" json:"arguments,omitempty"`
	Payable              bool          `protobuf:"varint,3,opt,name=payable,proto3" json:"payable,omitempty"`
	View                 bool          `protobuf:"varint,4,opt,name=view,proto3" json:"view,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Function) Reset()         { *m = Function{} }
func (m *Function) String() string { return proto.CompactTextString(m) }
func (*Function) ProtoMessage()    {}
func (*Function) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ac6287ce250c9a, []int{15}
}
func (m *Function) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Function.Unmarshal(m, b)
}
func (m *Function) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Function.Marshal(b, m, deterministic)
}
func (m *Function) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Function.Merge(m, src)
}
func (m *Function) XXX_Size() int {
	return xxx_messageInfo_Function.Size(m)
}
func (m *Function) XXX_DiscardUnknown() {
	xxx_messageInfo_Function.DiscardUnknown(m)
}

var xxx_messageInfo_Function proto.InternalMessageInfo

func (m *Function) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Function) GetArguments() []*FnArgument {
	if m != nil {
		return m.Arguments
	}
	return nil
}

func (m *Function) GetPayable() bool {
	if m != nil {
		return m.Payable
	}
	return false
}

func (m *Function) GetView() bool {
	if m != nil {
		return m.View
	}
	return false
}

type StateVar struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Len                  int32    `protobuf:"varint,3,opt,name=len,proto3" json:"len,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StateVar) Reset()         { *m = StateVar{} }
func (m *StateVar) String() string { return proto.CompactTextString(m) }
func (*StateVar) ProtoMessage()    {}
func (*StateVar) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ac6287ce250c9a, []int{16}
}
func (m *StateVar) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateVar.Unmarshal(m, b)
}
func (m *StateVar) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateVar.Marshal(b, m, deterministic)
}
func (m *StateVar) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateVar.Merge(m, src)
}
func (m *StateVar) XXX_Size() int {
	return xxx_messageInfo_StateVar.Size(m)
}
func (m *StateVar) XXX_DiscardUnknown() {
	xxx_messageInfo_StateVar.DiscardUnknown(m)
}

var xxx_messageInfo_StateVar proto.InternalMessageInfo

func (m *StateVar) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StateVar) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *StateVar) GetLen() int32 {
	if m != nil {
		return m.Len
	}
	return 0
}

type ABI struct {
	Version              string      `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Language             string      `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	Functions            []*Function `protobuf:"bytes,3,rep,name=functions,proto3" json:"functions,omitempty"`
	StateVariables       []*StateVar `protobuf:"bytes,4,rep,name=state_variables,json=stateVariables,proto3" json:"state_variables,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ABI) Reset()         { *m = ABI{} }
func (m *ABI) String() string { return proto.CompactTextString(m) }
func (*ABI) ProtoMessage()    {}
func (*ABI) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ac6287ce250c9a, []int{17}
}
func (m *ABI) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ABI.Unmarshal(m, b)
}
func (m *ABI) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ABI.Marshal(b, m, deterministic)
}
func (m *ABI) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ABI.Merge(m, src)
}
func (m *ABI) XXX_Size() int {
	return xxx_messageInfo_ABI.Size(m)
}
func (m *ABI) XXX_DiscardUnknown() {
	xxx_messageInfo_ABI.DiscardUnknown(m)
}

var xxx_messageInfo_ABI proto.InternalMessageInfo

func (m *ABI) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ABI) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *ABI) GetFunctions() []*Function {
	if m != nil {
		return m.Functions
	}
	return nil
}

func (m *ABI) GetStateVariables() []*StateVar {
	if m != nil {
		return m.StateVariables
	}
	return nil
}

type Query struct {
	ContractAddress      []byte   `protobuf:"bytes,1,opt,name=contractAddress,proto3" json:"contractAddress,omitempty"`
	Queryinfo            []byte   `protobuf:"bytes,2,opt,name=queryinfo,proto3" json:"queryinfo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Query) Reset()         { *m = Query{} }
func (m *Query) String() string { return proto.CompactTextString(m) }
func (*Query) ProtoMessage()    {}
func (*Query) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ac6287ce250c9a, []int{18}
}
func (m *Query) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Query.Unmarshal(m, b)
}
func (m *Query) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Query.Marshal(b, m, deterministic)
}
func (m *Query) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Query.Merge(m, src)
}
func (m *Query) XXX_Size() int {
	return xxx_messageInfo_Query.Size(m)
}
func (m *Query) XXX_DiscardUnknown() {
	xxx_messageInfo_Query.DiscardUnknown(m)
}

var xxx_messageInfo_Query proto.InternalMessageInfo

func (m *Query) GetContractAddress() []byte {
	if m != nil {
		return m.ContractAddress
	}
	return nil
}

func (m *Query) GetQueryinfo() []byte {
	if m != nil {
		return m.Queryinfo
	}
	return nil
}

type StateQuery struct {
	ContractAddress      []byte   `protobuf:"bytes,1,opt,name=contractAddress,proto3" json:"contractAddress,omitempty"`
	Root                 []byte   `protobuf:"bytes,3,opt,name=root,proto3" json:"root,omitempty"`
	Compressed           bool     `protobuf:"varint,4,opt,name=compressed,proto3" json:"compressed,omitempty"`
	StorageKeys          [][]byte `protobuf:"bytes,5,rep,name=storageKeys,proto3" json:"storageKeys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StateQuery) Reset()         { *m = StateQuery{} }
func (m *StateQuery) String() string { return proto.CompactTextString(m) }
func (*StateQuery) ProtoMessage()    {}
func (*StateQuery) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ac6287ce250c9a, []int{19}
}
func (m *StateQuery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateQuery.Unmarshal(m, b)
}
func (m *StateQuery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateQuery.Marshal(b, m, deterministic)
}
func (m *StateQuery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateQuery.Merge(m, src)
}
func (m *StateQuery) XXX_Size() int {
	return xxx_messageInfo_StateQuery.Size(m)
}
func (m *StateQuery) XXX_DiscardUnknown() {
	xxx_messageInfo_StateQuery.DiscardUnknown(m)
}

var xxx_messageInfo_StateQuery proto.InternalMessageInfo

func (m *StateQuery) GetContractAddress() []byte {
	if m != nil {
		return m.ContractAddress
	}
	return nil
}

func (m *StateQuery) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *StateQuery) GetCompressed() bool {
	if m != nil {
		return m.Compressed
	}
	return false
}

func (m *StateQuery) GetStorageKeys() [][]byte {
	if m != nil {
		return m.StorageKeys
	}
	return nil
}

type FilterInfo struct {
	ContractAddress      []byte   `protobuf:"bytes,1,opt,name=contractAddress,proto3" json:"contractAddress,omitempty"`
	EventName            string   `protobuf:"bytes,2,opt,name=eventName,proto3" json:"eventName,omitempty"`
	Blockfrom            uint64   `protobuf:"varint,3,opt,name=blockfrom,proto3" json:"blockfrom,omitempty"`
	Blockto              uint64   `protobuf:"varint,4,opt,name=blockto,proto3" json:"blockto,omitempty"`
	Desc                 bool     `protobuf:"varint,5,opt,name=desc,proto3" json:"desc,omitempty"`
	ArgFilter            []byte   `protobuf:"bytes,6,opt,name=argFilter,proto3" json:"argFilter,omitempty"`
	RecentBlockCnt       int32    `protobuf:"varint,7,opt,name=recentBlockCnt,proto3" json:"recentBlockCnt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FilterInfo) Reset()         { *m = FilterInfo{} }
func (m *FilterInfo) String() string { return proto.CompactTextString(m) }
func (*FilterInfo) ProtoMessage()    {}
func (*FilterInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_e9ac6287ce250c9a, []int{20}
}
func (m *FilterInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FilterInfo.Unmarshal(m, b)
}
func (m *FilterInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FilterInfo.Marshal(b, m, deterministic)
}
func (m *FilterInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FilterInfo.Merge(m, src)
}
func (m *FilterInfo) XXX_Size() int {
	return xxx_messageInfo_FilterInfo.Size(m)
}
func (m *FilterInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FilterInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FilterInfo proto.InternalMessageInfo

func (m *FilterInfo) GetContractAddress() []byte {
	if m != nil {
		return m.ContractAddress
	}
	return nil
}

func (m *FilterInfo) GetEventName() string {
	if m != nil {
		return m.EventName
	}
	return ""
}

func (m *FilterInfo) GetBlockfrom() uint64 {
	if m != nil {
		return m.Blockfrom
	}
	return 0
}

func (m *FilterInfo) GetBlockto() uint64 {
	if m != nil {
		return m.Blockto
	}
	return 0
}

func (m *FilterInfo) GetDesc() bool {
	if m != nil {
		return m.Desc
	}
	return false
}

func (m *FilterInfo) GetArgFilter() []byte {
	if m != nil {
		return m.ArgFilter
	}
	return nil
}

func (m *FilterInfo) GetRecentBlockCnt() int32 {
	if m != nil {
		return m.RecentBlockCnt
	}
	return 0
}

func init() {
	proto.RegisterType((*Block)(nil), "types.Block")
	proto.RegisterType((*BlockHeader)(nil), "types.BlockHeader")
	proto.RegisterType((*BlockBody)(nil), "types.BlockBody")
	proto.RegisterType((*TxList)(nil), "types.TxList")
	proto.RegisterType((*Tx)(nil), "types.Tx")
	proto.RegisterType((*TxBody)(nil), "types.TxBody")
	proto.RegisterType((*TxIdx)(nil), "types.TxIdx")
	proto.RegisterType((*TxInBlock)(nil), "types.TxInBlock")
	proto.RegisterType((*State)(nil), "types.State")
	proto.RegisterType((*AccountProof)(nil), "types.AccountProof")
	proto.RegisterType((*ContractVarProof)(nil), "types.ContractVarProof")
	proto.RegisterType((*StateQueryProof)(nil), "types.StateQueryProof")
	proto.RegisterType((*Receipt)(nil), "types.Receipt")
	proto.RegisterType((*Event)(nil), "types.Event")
	proto.RegisterType((*FnArgument)(nil), "types.FnArgument")
	proto.RegisterType((*Function)(nil), "types.Function")
	proto.RegisterType((*StateVar)(nil), "types.StateVar")
	proto.RegisterType((*ABI)(nil), "types.ABI")
	proto.RegisterType((*Query)(nil), "types.Query")
	proto.RegisterType((*StateQuery)(nil), "types.StateQuery")
	proto.RegisterType((*FilterInfo)(nil), "types.FilterInfo")
	proto.RegisterEnum("types.TxType", TxType_name, TxType_value)
}

func init() { proto.RegisterFile("blockchain.proto", fileDescriptor_e9ac6287ce250c9a) }

var fileDescriptor_e9ac6287ce250c9a = []byte{
	// 1342 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x57, 0xcd, 0x6e, 0x23, 0x45,
	0x10, 0x66, 0xec, 0x19, 0xc7, 0xae, 0xfc, 0x79, 0x9b, 0x15, 0x0c, 0xb0, 0x42, 0x66, 0xb4, 0xa0,
	0x68, 0x05, 0x8b, 0x14, 0x84, 0x00, 0x71, 0xca, 0xee, 0x26, 0xe0, 0xdd, 0x90, 0x84, 0x26, 0x44,
	0xe2, 0x84, 0xda, 0x33, 0x6d, 0x7b, 0x58, 0xcf, 0xb4, 0x77, 0xa6, 0x6d, 0xc6, 0x07, 0x4e, 0xbc,
	0x01, 0x37, 0x8e, 0x48, 0x3c, 0x1a, 0x42, 0x5c, 0x10, 0xe2, 0x0d, 0x50, 0x55, 0xf7, 0xfc, 0xd8,
	0x09, 0xa0, 0x95, 0x38, 0x70, 0xeb, 0xef, 0xeb, 0xea, 0x76, 0x55, 0x7d, 0x55, 0xd5, 0x63, 0xe8,
	0x8f, 0x66, 0x2a, 0x7c, 0x1a, 0x4e, 0x45, 0x9c, 0xde, 0x9f, 0x67, 0x4a, 0x2b, 0xe6, 0xe9, 0xd5,
	0x5c, 0xe6, 0x41, 0x02, 0xde, 0x03, 0xdc, 0x62, 0x0c, 0xdc, 0xa9, 0xc8, 0xa7, 0xbe, 0x33, 0x70,
	0x0e, 0x76, 0x38, 0xad, 0xd9, 0x3d, 0xe8, 0x4c, 0xa5, 0x88, 0x64, 0xe6, 0xb7, 0x06, 0xce, 0xc1,
	0xf6, 0x21, 0xbb, 0x4f, 0x87, 0xee, 0xd3, 0x89, 0x4f, 0x69, 0x87, 0x5b, 0x0b, 0x76, 0x17, 0xdc,
	0x91, 0x8a, 0x56, 0x7e, 0x9b, 0x2c, 0xfb, 0x4d, 0xcb, 0x07, 0x2a, 0x5a, 0x71, 0xda, 0x0d, 0x7e,
	0x6f, 0xc1, 0x76, 0xe3, 0x34, 0xf3, 0x61, 0x8b, 0x9c, 0x1a, 0x3e, 0xb2, 0x3f, 0x5c, 0x42, 0x76,
	0x17, 0x76, 0xe7, 0x99, 0x5c, 0x1a, 0x63, 0x74, 0xac, 0x45, 0xfb, 0xeb, 0x24, 0x9e, 0xa7, 0xc8,
	0xce, 0x14, 0xfd, 0xb0, 0xcb, 0x4b, 0xc8, 0xee, 0x40, 0x4f, 0xc7, 0x89, 0xcc, 0xb5, 0x48, 0xe6,
	0xbe, 0x3b, 0x70, 0x0e, 0xda, 0xbc, 0x26, 0xd8, 0x5b, 0xb0, 0x47, 0x86, 0x39, 0x57, 0x4a, 0xd3,
	0xf5, 0x1e, 0x5d, 0xbf, 0xc1, 0xb2, 0x01, 0x6c, 0xeb, 0xa2, 0x36, 0xea, 0x90, 0x51, 0x93, 0x62,
	0xf7, 0xa0, 0x9f, 0xc9, 0x50, 0xc6, 0x73, 0x5d, 0x9b, 0x6d, 0x91, 0xd9, 0x35, 0x9e, 0xbd, 0x0a,
	0xdd, 0x50, 0xa5, 0xe3, 0x38, 0x4b, 0x72, 0xbf, 0x4b, 0xee, 0x56, 0x98, 0xbd, 0x04, 0x9d, 0xf9,
	0x62, 0xf4, 0x44, 0xae, 0xfc, 0x1e, 0x9d, 0xb6, 0x88, 0x1d, 0xc0, 0x7e, 0xa8, 0xe2, 0x74, 0x24,
	0x72, 0x79, 0x14, 0x86, 0x6a, 0x91, 0x6a, 0x1f, 0xc8, 0x60, 0x93, 0x46, 0x05, 0xf3, 0x78, 0x92,
	0xfa, 0xdb, 0x46, 0x41, 0x5c, 0x07, 0x07, 0xd0, 0xab, 0x24, 0x60, 0xaf, 0x41, 0x5b, 0x17, 0xb9,
	0xef, 0x0c, 0xda, 0x07, 0xdb, 0x87, 0x3d, 0xab, 0xd0, 0x65, 0xc1, 0x91, 0x0d, 0xde, 0x84, 0xce,
	0x65, 0x71, 0x1a, 0xe7, 0xfa, 0x9f, 0xcd, 0x3e, 0x86, 0xd6, 0x65, 0x71, 0x63, 0xb1, 0xbc, 0x61,
	0x0b, 0xc0, 0x94, 0xca, 0x6e, 0x75, 0xae, 0xa1, 0xfe, 0x8f, 0x2d, 0xfc, 0x11, 0xf2, 0xe5, 0x36,
	0x78, 0xa9, 0x4a, 0x43, 0x49, 0x57, 0xb8, 0xdc, 0x00, 0x94, 0x53, 0xd8, 0x20, 0x8d, 0xdc, 0x25,
	0x44, 0x39, 0x33, 0x19, 0xc6, 0xf3, 0x58, 0xa6, 0x9a, 0xa4, 0xde, 0xe1, 0x35, 0x81, 0xc9, 0x13,
	0x09, 0x1d, 0x73, 0x4d, 0xf2, 0x0c, 0xc2, 0xfb, 0xe6, 0x62, 0x35, 0x53, 0x22, 0xb2, 0xfa, 0x96,
	0x10, 0xa5, 0x98, 0x88, 0xfc, 0x34, 0x4e, 0x62, 0x4d, 0xaa, 0xba, 0xbc, 0xc2, 0x76, 0xef, 0x22,
	0x8b, 0x43, 0x69, 0xa5, 0xac, 0x30, 0x46, 0x89, 0x81, 0x91, 0x7c, 0x7b, 0x8d, 0x28, 0x2f, 0x57,
	0x73, 0xc9, 0x69, 0x0b, 0x6b, 0xc6, 0x14, 0x71, 0x44, 0xc5, 0x60, 0xe4, 0x6c, 0x52, 0x95, 0x52,
	0xd0, 0x50, 0xea, 0x03, 0xf0, 0x2e, 0x8b, 0x61, 0x54, 0x60, 0xa4, 0xa3, 0xaa, 0xe8, 0x4d, 0x82,
	0x6b, 0x82, 0xf5, 0xa1, 0x1d, 0x47, 0x05, 0x65, 0xc7, 0xe3, 0xb8, 0x0c, 0x1e, 0x43, 0xef, 0xb2,
	0x18, 0xa6, 0xa6, 0x8b, 0x03, 0xf0, 0x34, 0xde, 0x42, 0x07, 0xb7, 0x0f, 0x77, 0x2a, 0xff, 0x86,
	0x51, 0xc1, 0xcd, 0x16, 0x7b, 0x05, 0x5a, 0xba, 0xb0, 0x32, 0x35, 0xe4, 0x6d, 0xe9, 0x22, 0xf8,
	0xc9, 0x01, 0xef, 0x0b, 0x2d, 0xb4, 0xfc, 0x7b, 0x7d, 0x46, 0x62, 0x26, 0x90, 0xb7, 0xfa, 0x58,
	0x68, 0x4a, 0x3b, 0x92, 0xe4, 0xb4, 0x91, 0xa7, 0xc2, 0x98, 0x90, 0x5c, 0xab, 0x4c, 0x4c, 0x24,
	0x76, 0x82, 0x95, 0xa8, 0x49, 0x61, 0x13, 0xe5, 0xcf, 0x66, 0x5c, 0x86, 0x6a, 0x29, 0xb3, 0xd5,
	0x85, 0x8a, 0x53, 0x4d, 0x82, 0xb9, 0xfc, 0x1a, 0x1f, 0xfc, 0xe6, 0xc0, 0x8e, 0x2d, 0xf9, 0x8b,
	0x4c, 0xa9, 0x31, 0xc6, 0x9c, 0xa3, 0xcf, 0x1b, 0x31, 0x53, 0x1c, 0xdc, 0x6c, 0x61, 0x52, 0xe3,
	0x34, 0x9c, 0x2d, 0xf2, 0x58, 0xa5, 0xe4, 0x7a, 0x97, 0xd7, 0x04, 0x26, 0xf5, 0xa9, 0x5c, 0x59,
	0xbf, 0x71, 0x89, 0xe1, 0xcc, 0xf1, 0x72, 0xec, 0x47, 0xe3, 0x6f, 0x85, 0xab, 0xbd, 0x2b, 0x31,
	0xb3, 0x55, 0x55, 0x61, 0x2c, 0xc4, 0x51, 0xac, 0x13, 0x31, 0xb7, 0xa3, 0xc2, 0x22, 0xe4, 0xa7,
	0x32, 0x9e, 0x4c, 0x35, 0x15, 0xd4, 0x2e, 0xb7, 0x08, 0xfd, 0x12, 0x8b, 0x28, 0xd6, 0x17, 0x42,
	0x4f, 0xfd, 0xee, 0xa0, 0x8d, 0x62, 0x57, 0x44, 0xf0, 0x8b, 0x03, 0xfd, 0x87, 0x2a, 0xd5, 0x99,
	0x08, 0xf5, 0x95, 0xc8, 0x4c, 0xb8, 0xb7, 0xc1, 0x5b, 0x8a, 0xd9, 0x42, 0xda, 0xda, 0x30, 0xe0,
	0x5f, 0x02, 0xfc, 0x5f, 0x84, 0x53, 0xa6, 0xb9, 0x57, 0xa5, 0xf9, 0xb1, 0xdb, 0x6d, 0xf7, 0xdd,
	0xe0, 0x7b, 0x07, 0xf6, 0x49, 0xad, 0xcf, 0x17, 0xa8, 0x32, 0x45, 0xf9, 0x11, 0xec, 0x86, 0x36,
	0x72, 0x22, 0xac, 0xb8, 0x2f, 0x5a, 0x71, 0x9b, 0x05, 0xc0, 0xd7, 0x2d, 0xd9, 0xfb, 0xd0, 0x5b,
	0xda, 0x64, 0xe5, 0x7e, 0x8b, 0xa6, 0xd8, 0xcb, 0xf6, 0xd8, 0x66, 0x32, 0x79, 0x6d, 0x19, 0xfc,
	0xd1, 0x82, 0x2d, 0x6e, 0x26, 0xb6, 0x19, 0xba, 0xc6, 0xf4, 0x28, 0x8a, 0x32, 0x99, 0xe7, 0x36,
	0xdb, 0x9b, 0x34, 0x66, 0x02, 0x2b, 0x6c, 0x91, 0x53, 0xd2, 0x7b, 0xdc, 0x22, 0x8c, 0x35, 0x93,
	0x66, 0x52, 0xf5, 0x38, 0x2e, 0xd1, 0x52, 0x17, 0xd4, 0x1f, 0x76, 0x46, 0x19, 0x84, 0x3d, 0x35,
	0x96, 0xf2, 0xcb, 0x5c, 0x56, 0x33, 0xca, 0x42, 0xf6, 0x36, 0xdc, 0x0a, 0x17, 0xc9, 0x62, 0x26,
	0x74, 0xbc, 0x94, 0x27, 0xd6, 0xc6, 0x08, 0x71, 0x7d, 0x03, 0xeb, 0x62, 0x34, 0x53, 0x2a, 0xb1,
	0x23, 0xcb, 0x00, 0x76, 0x17, 0x3a, 0x72, 0x29, 0x53, 0x9d, 0x93, 0x1c, 0x75, 0x77, 0x1c, 0x23,
	0xc9, 0xed, 0x5e, 0xf3, 0x19, 0xed, 0x5d, 0x7b, 0x46, 0xeb, 0x69, 0x04, 0x9b, 0xd3, 0xc8, 0x87,
	0x2d, 0x5d, 0x0c, 0xd3, 0x48, 0x16, 0xf4, 0xea, 0x78, 0xbc, 0x84, 0x38, 0xe2, 0xc6, 0x99, 0x4a,
	0xfc, 0x1d, 0x33, 0xe2, 0x70, 0xcd, 0xf6, 0xa0, 0xa5, 0x95, 0xbf, 0x4b, 0x4c, 0x4b, 0xab, 0xe0,
	0x4f, 0x07, 0x3c, 0xf2, 0xe3, 0x39, 0xf2, 0x7d, 0x07, 0x7a, 0xe4, 0xf3, 0x99, 0x48, 0xa4, 0x4d,
	0x79, 0x4d, 0x60, 0x2d, 0x7f, 0x93, 0xab, 0xf4, 0x28, 0x9b, 0xe4, 0x36, 0xf5, 0x15, 0xc6, 0x3d,
	0x32, 0xc4, 0xe9, 0xe8, 0x92, 0xb3, 0x15, 0x6e, 0x68, 0xe3, 0xad, 0x69, 0xb3, 0x16, 0x7d, 0xe7,
	0x86, 0xe8, 0xcb, 0xac, 0x6d, 0xad, 0x67, 0xad, 0x91, 0x97, 0xee, 0x5a, 0x5e, 0x82, 0x01, 0xc0,
	0x09, 0xfa, 0xb3, 0x48, 0xa4, 0x79, 0xb2, 0x53, 0x0c, 0xc4, 0x21, 0x5f, 0x69, 0x1d, 0x7c, 0x07,
	0xdd, 0x93, 0x45, 0x1a, 0x6a, 0xec, 0xdb, 0x1b, 0xf6, 0xd9, 0xbb, 0xd0, 0x13, 0xf6, 0x7c, 0x59,
	0xde, 0xb7, 0xac, 0xa8, 0xf5, 0xcd, 0xbc, 0xb6, 0xb1, 0x8f, 0xa0, 0x18, 0xcd, 0x24, 0xe5, 0xa4,
	0xcb, 0x4b, 0x88, 0xd7, 0x2f, 0x63, 0xf9, 0x2d, 0xa5, 0xa3, 0xcb, 0x69, 0x1d, 0x3c, 0x82, 0x2e,
	0xf5, 0xe2, 0x95, 0xc8, 0x6e, 0xfc, 0x79, 0x66, 0x1f, 0x40, 0x93, 0x7b, 0xf3, 0xe2, 0xf5, 0xa1,
	0x3d, 0x93, 0x29, 0xdd, 0xee, 0x71, 0x5c, 0x06, 0x3f, 0x3b, 0xd0, 0x3e, 0x7a, 0x30, 0xc4, 0xdf,
	0x5e, 0xca, 0x8c, 0x86, 0x92, 0xb9, 0xa4, 0x84, 0x28, 0xc7, 0x4c, 0xa4, 0x93, 0x85, 0x98, 0x94,
	0x77, 0x55, 0x98, 0xbd, 0x03, 0xbd, 0xb1, 0x4d, 0x01, 0xea, 0x88, 0x21, 0xee, 0x97, 0x21, 0x5a,
	0x9e, 0xd7, 0x16, 0xec, 0x43, 0xd8, 0xa7, 0x29, 0xff, 0xf5, 0x52, 0x64, 0x31, 0x06, 0x96, 0xfb,
	0xee, 0xda, 0xa1, 0x32, 0x20, 0xbe, 0x97, 0xdb, 0x95, 0x31, 0x0b, 0xce, 0xc1, 0xa3, 0x99, 0xf3,
	0x7c, 0x05, 0xf8, 0x0c, 0x8f, 0xc4, 0xe9, 0x58, 0xd9, 0x47, 0xb0, 0x26, 0x82, 0x1f, 0x1c, 0x80,
	0x7a, 0x94, 0x3d, 0xc7, 0xb5, 0x0c, 0xdc, 0x0c, 0x1f, 0x47, 0xf3, 0x06, 0xd1, 0x9a, 0xbd, 0x0e,
	0x10, 0xaa, 0x64, 0x8e, 0xfb, 0x32, 0xb2, 0x22, 0x35, 0x98, 0xc6, 0xbb, 0xfa, 0x44, 0xae, 0x72,
	0xdf, 0xa3, 0x79, 0xdb, 0xa4, 0x1e, 0xbb, 0xdd, 0x56, 0xbf, 0x1d, 0xfc, 0xea, 0x00, 0x9c, 0xc4,
	0x33, 0x2d, 0xb3, 0x61, 0x3a, 0x56, 0xff, 0x59, 0xb3, 0x95, 0xcd, 0x41, 0x7d, 0x6e, 0xbe, 0xbe,
	0x6b, 0xa2, 0x6a, 0x0e, 0xad, 0xc8, 0xf3, 0xb2, 0x39, 0xb4, 0xc2, 0x50, 0x23, 0x99, 0x87, 0xd4,
	0x6a, 0x5d, 0x4e, 0x6b, 0x7a, 0x38, 0xb2, 0x89, 0x71, 0xb2, 0x6c, 0xb4, 0x8a, 0xc0, 0xaf, 0x75,
	0xfc, 0x96, 0x4e, 0x35, 0x7d, 0xe4, 0x3c, 0x4c, 0xcd, 0xb3, 0xe3, 0xf1, 0x0d, 0xf6, 0xde, 0x21,
	0x7e, 0x5e, 0xe2, 0x97, 0x18, 0x03, 0xe8, 0x9c, 0x9d, 0xf3, 0xcf, 0x8e, 0x4e, 0xfb, 0x2f, 0xb0,
	0x3d, 0x80, 0x4f, 0xce, 0xaf, 0x8e, 0xf9, 0xd9, 0xd1, 0xd9, 0xc3, 0xe3, 0xbe, 0xc3, 0x76, 0xa0,
	0xcb, 0x8f, 0x1f, 0x1d, 0x5f, 0x9c, 0x9e, 0x7f, 0xd5, 0x6f, 0x8d, 0x3a, 0xf4, 0x77, 0xe8, 0xbd,
	0xbf, 0x02, 0x00, 0x00, 0xff, 0xff, 0xc2, 0xbc, 0x4c, 0x2e, 0x22, 0x0d, 0x00, 0x00,
}
