// Code generated by protoc-gen-go. DO NOT EDIT.
// source: metric.proto

package types // import "/types"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MetricType int32

const (
	// NOTHING should not be used.
	MetricType_NOTHING MetricType = 0
	// Metric for p2p network transfer
	MetricType_P2P_NETWORK MetricType = 1
)

var MetricType_name = map[int32]string{
	0: "NOTHING",
	1: "P2P_NETWORK",
}
var MetricType_value = map[string]int32{
	"NOTHING":     0,
	"P2P_NETWORK": 1,
}

func (x MetricType) String() string {
	return proto.EnumName(MetricType_name, int32(x))
}
func (MetricType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_metric_ba2d8354bd6c7070, []int{0}
}

type MetricsRequest struct {
	Types                []MetricType `protobuf:"varint,1,rep,packed,name=types,enum=types.MetricType" json:"types,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *MetricsRequest) Reset()         { *m = MetricsRequest{} }
func (m *MetricsRequest) String() string { return proto.CompactTextString(m) }
func (*MetricsRequest) ProtoMessage()    {}
func (*MetricsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_metric_ba2d8354bd6c7070, []int{0}
}
func (m *MetricsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricsRequest.Unmarshal(m, b)
}
func (m *MetricsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricsRequest.Marshal(b, m, deterministic)
}
func (dst *MetricsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricsRequest.Merge(dst, src)
}
func (m *MetricsRequest) XXX_Size() int {
	return xxx_messageInfo_MetricsRequest.Size(m)
}
func (m *MetricsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MetricsRequest proto.InternalMessageInfo

func (m *MetricsRequest) GetTypes() []MetricType {
	if m != nil {
		return m.Types
	}
	return nil
}

type Metrics struct {
	Peers                []*PeerMetric `protobuf:"bytes,1,rep,name=peers" json:"peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Metrics) Reset()         { *m = Metrics{} }
func (m *Metrics) String() string { return proto.CompactTextString(m) }
func (*Metrics) ProtoMessage()    {}
func (*Metrics) Descriptor() ([]byte, []int) {
	return fileDescriptor_metric_ba2d8354bd6c7070, []int{1}
}
func (m *Metrics) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metrics.Unmarshal(m, b)
}
func (m *Metrics) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metrics.Marshal(b, m, deterministic)
}
func (dst *Metrics) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metrics.Merge(dst, src)
}
func (m *Metrics) XXX_Size() int {
	return xxx_messageInfo_Metrics.Size(m)
}
func (m *Metrics) XXX_DiscardUnknown() {
	xxx_messageInfo_Metrics.DiscardUnknown(m)
}

var xxx_messageInfo_Metrics proto.InternalMessageInfo

func (m *Metrics) GetPeers() []*PeerMetric {
	if m != nil {
		return m.Peers
	}
	return nil
}

type PeerMetric struct {
	PeerID               []byte   `protobuf:"bytes,1,opt,name=peerID,proto3" json:"peerID,omitempty"`
	SumIn                int64    `protobuf:"varint,2,opt,name=sumIn" json:"sumIn,omitempty"`
	AvrIn                int64    `protobuf:"varint,3,opt,name=avrIn" json:"avrIn,omitempty"`
	SumOut               int64    `protobuf:"varint,4,opt,name=sumOut" json:"sumOut,omitempty"`
	AvrOut               int64    `protobuf:"varint,5,opt,name=avrOut" json:"avrOut,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerMetric) Reset()         { *m = PeerMetric{} }
func (m *PeerMetric) String() string { return proto.CompactTextString(m) }
func (*PeerMetric) ProtoMessage()    {}
func (*PeerMetric) Descriptor() ([]byte, []int) {
	return fileDescriptor_metric_ba2d8354bd6c7070, []int{2}
}
func (m *PeerMetric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerMetric.Unmarshal(m, b)
}
func (m *PeerMetric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerMetric.Marshal(b, m, deterministic)
}
func (dst *PeerMetric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerMetric.Merge(dst, src)
}
func (m *PeerMetric) XXX_Size() int {
	return xxx_messageInfo_PeerMetric.Size(m)
}
func (m *PeerMetric) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerMetric.DiscardUnknown(m)
}

var xxx_messageInfo_PeerMetric proto.InternalMessageInfo

func (m *PeerMetric) GetPeerID() []byte {
	if m != nil {
		return m.PeerID
	}
	return nil
}

func (m *PeerMetric) GetSumIn() int64 {
	if m != nil {
		return m.SumIn
	}
	return 0
}

func (m *PeerMetric) GetAvrIn() int64 {
	if m != nil {
		return m.AvrIn
	}
	return 0
}

func (m *PeerMetric) GetSumOut() int64 {
	if m != nil {
		return m.SumOut
	}
	return 0
}

func (m *PeerMetric) GetAvrOut() int64 {
	if m != nil {
		return m.AvrOut
	}
	return 0
}

func init() {
	proto.RegisterType((*MetricsRequest)(nil), "types.MetricsRequest")
	proto.RegisterType((*Metrics)(nil), "types.Metrics")
	proto.RegisterType((*PeerMetric)(nil), "types.PeerMetric")
	proto.RegisterEnum("types.MetricType", MetricType_name, MetricType_value)
}

func init() { proto.RegisterFile("metric.proto", fileDescriptor_metric_ba2d8354bd6c7070) }

var fileDescriptor_metric_ba2d8354bd6c7070 = []byte{
	// 234 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0x90, 0xcf, 0x4b, 0xc3, 0x30,
	0x14, 0x80, 0x8d, 0xb5, 0x9d, 0xbc, 0x8e, 0x39, 0x83, 0x48, 0x8e, 0x65, 0x17, 0xcb, 0x0e, 0x15,
	0xea, 0xc9, 0xab, 0x28, 0x5a, 0xc4, 0xb6, 0x84, 0x82, 0xe0, 0x45, 0xa6, 0xbc, 0x83, 0x87, 0x6e,
	0x31, 0x3f, 0x06, 0xbb, 0xf9, 0xa7, 0x4b, 0xf2, 0xc2, 0x7a, 0xfc, 0xbe, 0xf7, 0xbe, 0xc0, 0x0b,
	0xcc, 0x47, 0xb4, 0xfa, 0xe7, 0xbb, 0x52, 0x7a, 0x67, 0x77, 0x3c, 0xb5, 0x07, 0x85, 0x66, 0x75,
	0x0f, 0x8b, 0xb7, 0xa0, 0x8d, 0xc4, 0x5f, 0x87, 0xc6, 0xf2, 0x1b, 0xa0, 0x91, 0x60, 0x45, 0x52,
	0x2e, 0xea, 0xcb, 0x2a, 0x50, 0x45, 0x5b, 0xc3, 0x41, 0xa1, 0x8c, 0x69, 0x0d, 0xb3, 0x98, 0xfa,
	0x46, 0x21, 0x6a, 0x6a, 0xf2, 0x63, 0xd3, 0x23, 0x6a, 0x5a, 0x91, 0x34, 0x5f, 0xfd, 0x31, 0x80,
	0xc9, 0xf2, 0x6b, 0xc8, 0xbc, 0x6f, 0x1e, 0x05, 0x2b, 0x58, 0x39, 0x97, 0x91, 0xf8, 0x15, 0xa4,
	0xc6, 0x8d, 0xcd, 0x56, 0x9c, 0x16, 0xac, 0x4c, 0x24, 0x81, 0xb7, 0x9b, 0xbd, 0x6e, 0xb6, 0x22,
	0x21, 0x1b, 0xc0, 0xbf, 0x61, 0xdc, 0xd8, 0x39, 0x2b, 0xce, 0x82, 0x8e, 0xe4, 0xfd, 0x66, 0xaf,
	0xbd, 0x4f, 0xc9, 0x13, 0xad, 0xd7, 0x00, 0xd3, 0x2d, 0x3c, 0x87, 0x59, 0xdb, 0x0d, 0x2f, 0x4d,
	0xfb, 0xbc, 0x3c, 0xe1, 0x17, 0x90, 0xf7, 0x75, 0xff, 0xd9, 0x3e, 0x0d, 0xef, 0x9d, 0x7c, 0x5d,
	0xb2, 0x87, 0xf3, 0x8f, 0xec, 0x36, 0x9c, 0xf2, 0x95, 0x85, 0x5f, 0xbb, 0xfb, 0x0f, 0x00, 0x00,
	0xff, 0xff, 0xc7, 0xe9, 0x58, 0x87, 0x45, 0x01, 0x00, 0x00,
}
