// Code generated by protoc-gen-go. DO NOT EDIT.
// source: node.proto

package types // import "/types"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PeerRole int32

const (
	PeerRole_LegacyVersion PeerRole = 0
	PeerRole_Producer      PeerRole = 1
	PeerRole_Watcher       PeerRole = 2
	PeerRole_Agent         PeerRole = 3
)

var PeerRole_name = map[int32]string{
	0: "LegacyVersion",
	1: "Producer",
	2: "Watcher",
	3: "Agent",
}
var PeerRole_value = map[string]int32{
	"LegacyVersion": 0,
	"Producer":      1,
	"Watcher":       2,
	"Agent":         3,
}

func (x PeerRole) String() string {
	return proto.EnumName(PeerRole_name, int32(x))
}
func (PeerRole) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_node_b004af9443c76acc, []int{0}
}

// PeerAddress contains static information of peer and addresses to connect peer
type PeerAddress struct {
	// @Deprecated advertised address and port will be in addresses field in aergo v2.
	// address is string representation of ip address or domain name.
	Address string `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	// @Deprecated
	Port                 uint32   `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
	PeerID               []byte   `protobuf:"bytes,3,opt,name=peerID,proto3" json:"peerID,omitempty"`
	Role                 PeerRole `protobuf:"varint,4,opt,name=role,enum=types.PeerRole" json:"role,omitempty"`
	Version              string   `protobuf:"bytes,5,opt,name=version" json:"version,omitempty"`
	Addresses            []string `protobuf:"bytes,6,rep,name=addresses" json:"addresses,omitempty"`
	ProducerIDs          [][]byte `protobuf:"bytes,7,rep,name=producerIDs,proto3" json:"producerIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerAddress) Reset()         { *m = PeerAddress{} }
func (m *PeerAddress) String() string { return proto.CompactTextString(m) }
func (*PeerAddress) ProtoMessage()    {}
func (*PeerAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_b004af9443c76acc, []int{0}
}
func (m *PeerAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerAddress.Unmarshal(m, b)
}
func (m *PeerAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerAddress.Marshal(b, m, deterministic)
}
func (dst *PeerAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerAddress.Merge(dst, src)
}
func (m *PeerAddress) XXX_Size() int {
	return xxx_messageInfo_PeerAddress.Size(m)
}
func (m *PeerAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerAddress.DiscardUnknown(m)
}

var xxx_messageInfo_PeerAddress proto.InternalMessageInfo

func (m *PeerAddress) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *PeerAddress) GetPort() uint32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *PeerAddress) GetPeerID() []byte {
	if m != nil {
		return m.PeerID
	}
	return nil
}

func (m *PeerAddress) GetRole() PeerRole {
	if m != nil {
		return m.Role
	}
	return PeerRole_LegacyVersion
}

func (m *PeerAddress) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *PeerAddress) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *PeerAddress) GetProducerIDs() [][]byte {
	if m != nil {
		return m.ProducerIDs
	}
	return nil
}

type AgentCertificate struct {
	CertVersion uint32 `protobuf:"varint,1,opt,name=certVersion" json:"certVersion,omitempty"`
	BPID        []byte `protobuf:"bytes,2,opt,name=BPID,proto3" json:"BPID,omitempty"`
	BPPubKey    []byte `protobuf:"bytes,3,opt,name=BPPubKey,proto3" json:"BPPubKey,omitempty"`
	// CreateTime is the number of nanoseconds elapsed since January 1, 1970 UTC
	CreateTime int64 `protobuf:"varint,4,opt,name=createTime" json:"createTime,omitempty"`
	// CreateTime is the number of nanoseconds elapsed since January 1, 1970 UTC
	ExpireTime           int64    `protobuf:"varint,5,opt,name=expireTime" json:"expireTime,omitempty"`
	AgentID              []byte   `protobuf:"bytes,6,opt,name=agentID,proto3" json:"agentID,omitempty"`
	AgentAddress         [][]byte `protobuf:"bytes,7,rep,name=AgentAddress,proto3" json:"AgentAddress,omitempty"`
	Signature            []byte   `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentCertificate) Reset()         { *m = AgentCertificate{} }
func (m *AgentCertificate) String() string { return proto.CompactTextString(m) }
func (*AgentCertificate) ProtoMessage()    {}
func (*AgentCertificate) Descriptor() ([]byte, []int) {
	return fileDescriptor_node_b004af9443c76acc, []int{1}
}
func (m *AgentCertificate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentCertificate.Unmarshal(m, b)
}
func (m *AgentCertificate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentCertificate.Marshal(b, m, deterministic)
}
func (dst *AgentCertificate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentCertificate.Merge(dst, src)
}
func (m *AgentCertificate) XXX_Size() int {
	return xxx_messageInfo_AgentCertificate.Size(m)
}
func (m *AgentCertificate) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentCertificate.DiscardUnknown(m)
}

var xxx_messageInfo_AgentCertificate proto.InternalMessageInfo

func (m *AgentCertificate) GetCertVersion() uint32 {
	if m != nil {
		return m.CertVersion
	}
	return 0
}

func (m *AgentCertificate) GetBPID() []byte {
	if m != nil {
		return m.BPID
	}
	return nil
}

func (m *AgentCertificate) GetBPPubKey() []byte {
	if m != nil {
		return m.BPPubKey
	}
	return nil
}

func (m *AgentCertificate) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *AgentCertificate) GetExpireTime() int64 {
	if m != nil {
		return m.ExpireTime
	}
	return 0
}

func (m *AgentCertificate) GetAgentID() []byte {
	if m != nil {
		return m.AgentID
	}
	return nil
}

func (m *AgentCertificate) GetAgentAddress() [][]byte {
	if m != nil {
		return m.AgentAddress
	}
	return nil
}

func (m *AgentCertificate) GetSignature() []byte {
	if m != nil {
		return m.Signature
	}
	return nil
}

func init() {
	proto.RegisterType((*PeerAddress)(nil), "types.PeerAddress")
	proto.RegisterType((*AgentCertificate)(nil), "types.AgentCertificate")
	proto.RegisterEnum("types.PeerRole", PeerRole_name, PeerRole_value)
}

func init() { proto.RegisterFile("node.proto", fileDescriptor_node_b004af9443c76acc) }

var fileDescriptor_node_b004af9443c76acc = []byte{
	// 364 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x92, 0x4f, 0x6b, 0xe3, 0x30,
	0x10, 0xc5, 0x57, 0x71, 0xec, 0xd8, 0x13, 0x67, 0xd7, 0x3b, 0x87, 0x45, 0x2c, 0xcb, 0x62, 0xb2,
	0x17, 0xb3, 0x87, 0x14, 0xda, 0x4f, 0x90, 0x3f, 0x97, 0xd0, 0x1e, 0x8c, 0x28, 0x2d, 0xf4, 0xe6,
	0xd8, 0xd3, 0xd4, 0x90, 0x5a, 0x46, 0x56, 0x4a, 0x73, 0xeb, 0x67, 0xec, 0x27, 0x2a, 0x92, 0x95,
	0x26, 0xbd, 0xcd, 0x7b, 0x83, 0xfc, 0xd3, 0x7b, 0x32, 0x40, 0x23, 0x2b, 0x9a, 0xb5, 0x4a, 0x6a,
	0x89, 0xbe, 0x3e, 0xb4, 0xd4, 0x4d, 0xdf, 0x19, 0x8c, 0x73, 0x22, 0x35, 0xaf, 0x2a, 0x45, 0x5d,
	0x87, 0x1c, 0x46, 0x45, 0x3f, 0x72, 0x96, 0xb2, 0x2c, 0x12, 0x47, 0x89, 0x08, 0xc3, 0x56, 0x2a,
	0xcd, 0x07, 0x29, 0xcb, 0x26, 0xc2, 0xce, 0xf8, 0x0b, 0x82, 0x96, 0x48, 0xad, 0x57, 0xdc, 0x4b,
	0x59, 0x16, 0x0b, 0xa7, 0xf0, 0x1f, 0x0c, 0x95, 0xdc, 0x11, 0x1f, 0xa6, 0x2c, 0xfb, 0x7e, 0xf9,
	0x63, 0x66, 0x59, 0x33, 0xc3, 0x11, 0x72, 0x47, 0xc2, 0x2e, 0x0d, 0xea, 0x85, 0x54, 0x57, 0xcb,
	0x86, 0xfb, 0x3d, 0xca, 0x49, 0xfc, 0x03, 0x91, 0xa3, 0x52, 0xc7, 0x83, 0xd4, 0xcb, 0x22, 0x71,
	0x32, 0x30, 0x85, 0x71, 0xab, 0x64, 0xb5, 0x2f, 0x0d, 0xaa, 0xe3, 0xa3, 0xd4, 0xcb, 0x62, 0x71,
	0x6e, 0x4d, 0xdf, 0x06, 0x90, 0xcc, 0xb7, 0xd4, 0xe8, 0x25, 0x29, 0x5d, 0x3f, 0xd6, 0x65, 0xa1,
	0xc9, 0x1c, 0x2b, 0x49, 0xe9, 0x3b, 0x87, 0x64, 0x36, 0xc6, 0xb9, 0x65, 0x12, 0x2e, 0xf2, 0xf5,
	0xca, 0x26, 0x8c, 0x85, 0x9d, 0xf1, 0x37, 0x84, 0x8b, 0x3c, 0xdf, 0x6f, 0xae, 0xe9, 0xe0, 0x32,
	0x7e, 0x6a, 0xfc, 0x0b, 0x50, 0x2a, 0x2a, 0x34, 0xdd, 0xd6, 0xcf, 0x7d, 0x56, 0x4f, 0x9c, 0x39,
	0x66, 0x4f, 0xaf, 0x6d, 0xad, 0xfa, 0xbd, 0xdf, 0xef, 0x4f, 0x8e, 0xed, 0xda, 0xdc, 0x72, 0xbd,
	0xe2, 0x81, 0xfd, 0xf4, 0x51, 0xe2, 0x14, 0x62, 0x7b, 0x7f, 0xf7, 0x2a, 0x2e, 0xe3, 0x17, 0xcf,
	0x94, 0xd4, 0xd5, 0xdb, 0xa6, 0xd0, 0x7b, 0x45, 0x3c, 0xb4, 0xe7, 0x4f, 0xc6, 0xff, 0x25, 0x84,
	0xc7, 0xba, 0xf1, 0x27, 0x4c, 0x6e, 0x68, 0x5b, 0x94, 0x07, 0x17, 0x34, 0xf9, 0x86, 0x31, 0x84,
	0xb9, 0x2b, 0x2c, 0x61, 0x38, 0x86, 0xd1, 0x7d, 0xa1, 0xcb, 0x27, 0x52, 0xc9, 0x00, 0x23, 0xf0,
	0x2d, 0x27, 0xf1, 0x16, 0xe1, 0x43, 0x70, 0x61, 0x9f, 0x6e, 0x13, 0xd8, 0x9f, 0xe6, 0xea, 0x23,
	0x00, 0x00, 0xff, 0xff, 0x97, 0x9f, 0x64, 0x8b, 0x42, 0x02, 0x00, 0x00,
}
