// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package types

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CommitStatus int32

const (
	CommitStatus_TX_OK                   CommitStatus = 0
	CommitStatus_TX_NONCE_TOO_LOW        CommitStatus = 1
	CommitStatus_TX_ALREADY_EXISTS       CommitStatus = 2
	CommitStatus_TX_INVALID_HASH         CommitStatus = 3
	CommitStatus_TX_INVALID_SIGN         CommitStatus = 4
	CommitStatus_TX_INVALID_FORMAT       CommitStatus = 5
	CommitStatus_TX_INSUFFICIENT_BALANCE CommitStatus = 6
	CommitStatus_TX_HAS_SAME_NONCE       CommitStatus = 7
	CommitStatus_TX_INTERNAL_ERROR       CommitStatus = 9
)

var CommitStatus_name = map[int32]string{
	0: "TX_OK",
	1: "TX_NONCE_TOO_LOW",
	2: "TX_ALREADY_EXISTS",
	3: "TX_INVALID_HASH",
	4: "TX_INVALID_SIGN",
	5: "TX_INVALID_FORMAT",
	6: "TX_INSUFFICIENT_BALANCE",
	7: "TX_HAS_SAME_NONCE",
	9: "TX_INTERNAL_ERROR",
}

var CommitStatus_value = map[string]int32{
	"TX_OK":                   0,
	"TX_NONCE_TOO_LOW":        1,
	"TX_ALREADY_EXISTS":       2,
	"TX_INVALID_HASH":         3,
	"TX_INVALID_SIGN":         4,
	"TX_INVALID_FORMAT":       5,
	"TX_INSUFFICIENT_BALANCE": 6,
	"TX_HAS_SAME_NONCE":       7,
	"TX_INTERNAL_ERROR":       9,
}

func (x CommitStatus) String() string {
	return proto.EnumName(CommitStatus_name, int32(x))
}

func (CommitStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

type VerifyStatus int32

const (
	VerifyStatus_VERIFY_STATUS_OK             VerifyStatus = 0
	VerifyStatus_VERIFY_STATUS_SIGN_NOT_MATCH VerifyStatus = 1
	VerifyStatus_VERIFY_STATUS_INVALID_HASH   VerifyStatus = 2
)

var VerifyStatus_name = map[int32]string{
	0: "VERIFY_STATUS_OK",
	1: "VERIFY_STATUS_SIGN_NOT_MATCH",
	2: "VERIFY_STATUS_INVALID_HASH",
}

var VerifyStatus_value = map[string]int32{
	"VERIFY_STATUS_OK":             0,
	"VERIFY_STATUS_SIGN_NOT_MATCH": 1,
	"VERIFY_STATUS_INVALID_HASH":   2,
}

func (x VerifyStatus) String() string {
	return proto.EnumName(VerifyStatus_name, int32(x))
}

func (VerifyStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{1}
}

// BlockchainStatus is current status of blockchain
type BlockchainStatus struct {
	BestBlockHash        []byte     `protobuf:"bytes,1,opt,name=best_block_hash,json=bestBlockHash,proto3" json:"best_block_hash,omitempty"`
	BestHeight           uint64     `protobuf:"varint,2,opt,name=best_height,json=bestHeight,proto3" json:"best_height,omitempty"`
	ConsensusInfo        string     `protobuf:"bytes,3,opt,name=consensus_info,json=consensusInfo,proto3" json:"consensus_info,omitempty"`
	BestChainIdHash      []byte     `protobuf:"bytes,4,opt,name=best_chain_id_hash,json=bestChainIdHash,proto3" json:"best_chain_id_hash,omitempty"`
	ChainInfo            *ChainInfo `protobuf:"bytes,5,opt,name=chain_info,json=chainInfo,proto3" json:"chain_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *BlockchainStatus) Reset()         { *m = BlockchainStatus{} }
func (m *BlockchainStatus) String() string { return proto.CompactTextString(m) }
func (*BlockchainStatus) ProtoMessage()    {}
func (*BlockchainStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

func (m *BlockchainStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockchainStatus.Unmarshal(m, b)
}
func (m *BlockchainStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockchainStatus.Marshal(b, m, deterministic)
}
func (m *BlockchainStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockchainStatus.Merge(m, src)
}
func (m *BlockchainStatus) XXX_Size() int {
	return xxx_messageInfo_BlockchainStatus.Size(m)
}
func (m *BlockchainStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockchainStatus.DiscardUnknown(m)
}

var xxx_messageInfo_BlockchainStatus proto.InternalMessageInfo

func (m *BlockchainStatus) GetBestBlockHash() []byte {
	if m != nil {
		return m.BestBlockHash
	}
	return nil
}

func (m *BlockchainStatus) GetBestHeight() uint64 {
	if m != nil {
		return m.BestHeight
	}
	return 0
}

func (m *BlockchainStatus) GetConsensusInfo() string {
	if m != nil {
		return m.ConsensusInfo
	}
	return ""
}

func (m *BlockchainStatus) GetBestChainIdHash() []byte {
	if m != nil {
		return m.BestChainIdHash
	}
	return nil
}

func (m *BlockchainStatus) GetChainInfo() *ChainInfo {
	if m != nil {
		return m.ChainInfo
	}
	return nil
}

type ChainId struct {
	Magic                string   `protobuf:"bytes,1,opt,name=magic,proto3" json:"magic,omitempty"`
	Public               bool     `protobuf:"varint,2,opt,name=public,proto3" json:"public,omitempty"`
	Mainnet              bool     `protobuf:"varint,3,opt,name=mainnet,proto3" json:"mainnet,omitempty"`
	Consensus            string   `protobuf:"bytes,4,opt,name=consensus,proto3" json:"consensus,omitempty"`
	Version              int32    `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChainId) Reset()         { *m = ChainId{} }
func (m *ChainId) String() string { return proto.CompactTextString(m) }
func (*ChainId) ProtoMessage()    {}
func (*ChainId) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{1}
}

func (m *ChainId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainId.Unmarshal(m, b)
}
func (m *ChainId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainId.Marshal(b, m, deterministic)
}
func (m *ChainId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainId.Merge(m, src)
}
func (m *ChainId) XXX_Size() int {
	return xxx_messageInfo_ChainId.Size(m)
}
func (m *ChainId) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainId.DiscardUnknown(m)
}

var xxx_messageInfo_ChainId proto.InternalMessageInfo

func (m *ChainId) GetMagic() string {
	if m != nil {
		return m.Magic
	}
	return ""
}

func (m *ChainId) GetPublic() bool {
	if m != nil {
		return m.Public
	}
	return false
}

func (m *ChainId) GetMainnet() bool {
	if m != nil {
		return m.Mainnet
	}
	return false
}

func (m *ChainId) GetConsensus() string {
	if m != nil {
		return m.Consensus
	}
	return ""
}

func (m *ChainId) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

// ChainInfo returns chain configuration
type ChainInfo struct {
	Id                   *ChainId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BpNumber             uint32   `protobuf:"varint,2,opt,name=bpNumber,proto3" json:"bpNumber,omitempty"`
	Maxblocksize         uint64   `protobuf:"varint,3,opt,name=maxblocksize,proto3" json:"maxblocksize,omitempty"`
	Maxtokens            []byte   `protobuf:"bytes,4,opt,name=maxtokens,proto3" json:"maxtokens,omitempty"`
	Stakingminimum       []byte   `protobuf:"bytes,5,opt,name=stakingminimum,proto3" json:"stakingminimum,omitempty"`
	Totalstaking         []byte   `protobuf:"bytes,6,opt,name=totalstaking,proto3" json:"totalstaking,omitempty"`
	Gasprice             []byte   `protobuf:"bytes,7,opt,name=gasprice,proto3" json:"gasprice,omitempty"`
	Nameprice            []byte   `protobuf:"bytes,8,opt,name=nameprice,proto3" json:"nameprice,omitempty"`
	Totalvotingpower     []byte   `protobuf:"bytes,9,opt,name=totalvotingpower,proto3" json:"totalvotingpower,omitempty"`
	Votingreward         []byte   `protobuf:"bytes,10,opt,name=votingreward,proto3" json:"votingreward,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChainInfo) Reset()         { *m = ChainInfo{} }
func (m *ChainInfo) String() string { return proto.CompactTextString(m) }
func (*ChainInfo) ProtoMessage()    {}
func (*ChainInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{2}
}

func (m *ChainInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainInfo.Unmarshal(m, b)
}
func (m *ChainInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainInfo.Marshal(b, m, deterministic)
}
func (m *ChainInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainInfo.Merge(m, src)
}
func (m *ChainInfo) XXX_Size() int {
	return xxx_messageInfo_ChainInfo.Size(m)
}
func (m *ChainInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ChainInfo proto.InternalMessageInfo

func (m *ChainInfo) GetId() *ChainId {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ChainInfo) GetBpNumber() uint32 {
	if m != nil {
		return m.BpNumber
	}
	return 0
}

func (m *ChainInfo) GetMaxblocksize() uint64 {
	if m != nil {
		return m.Maxblocksize
	}
	return 0
}

func (m *ChainInfo) GetMaxtokens() []byte {
	if m != nil {
		return m.Maxtokens
	}
	return nil
}

func (m *ChainInfo) GetStakingminimum() []byte {
	if m != nil {
		return m.Stakingminimum
	}
	return nil
}

func (m *ChainInfo) GetTotalstaking() []byte {
	if m != nil {
		return m.Totalstaking
	}
	return nil
}

func (m *ChainInfo) GetGasprice() []byte {
	if m != nil {
		return m.Gasprice
	}
	return nil
}

func (m *ChainInfo) GetNameprice() []byte {
	if m != nil {
		return m.Nameprice
	}
	return nil
}

func (m *ChainInfo) GetTotalvotingpower() []byte {
	if m != nil {
		return m.Totalvotingpower
	}
	return nil
}

func (m *ChainInfo) GetVotingreward() []byte {
	if m != nil {
		return m.Votingreward
	}
	return nil
}

// ChainStats corresponds to a chain statistics report.
type ChainStats struct {
	Report               string   `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChainStats) Reset()         { *m = ChainStats{} }
func (m *ChainStats) String() string { return proto.CompactTextString(m) }
func (*ChainStats) ProtoMessage()    {}
func (*ChainStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{3}
}

func (m *ChainStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChainStats.Unmarshal(m, b)
}
func (m *ChainStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChainStats.Marshal(b, m, deterministic)
}
func (m *ChainStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChainStats.Merge(m, src)
}
func (m *ChainStats) XXX_Size() int {
	return xxx_messageInfo_ChainStats.Size(m)
}
func (m *ChainStats) XXX_DiscardUnknown() {
	xxx_messageInfo_ChainStats.DiscardUnknown(m)
}

var xxx_messageInfo_ChainStats proto.InternalMessageInfo

func (m *ChainStats) GetReport() string {
	if m != nil {
		return m.Report
	}
	return ""
}

type Input struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Address              [][]byte `protobuf:"bytes,2,rep,name=address,proto3" json:"address,omitempty"`
	Value                []byte   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Script               []byte   `protobuf:"bytes,4,opt,name=script,proto3" json:"script,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Input) Reset()         { *m = Input{} }
func (m *Input) String() string { return proto.CompactTextString(m) }
func (*Input) ProtoMessage()    {}
func (*Input) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{4}
}

func (m *Input) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Input.Unmarshal(m, b)
}
func (m *Input) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Input.Marshal(b, m, deterministic)
}
func (m *Input) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Input.Merge(m, src)
}
func (m *Input) XXX_Size() int {
	return xxx_messageInfo_Input.Size(m)
}
func (m *Input) XXX_DiscardUnknown() {
	xxx_messageInfo_Input.DiscardUnknown(m)
}

var xxx_messageInfo_Input proto.InternalMessageInfo

func (m *Input) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *Input) GetAddress() [][]byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Input) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Input) GetScript() []byte {
	if m != nil {
		return m.Script
	}
	return nil
}

type Output struct {
	Index                uint32   `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	Address              []byte   `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Value                []byte   `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	Script               []byte   `protobuf:"bytes,4,opt,name=script,proto3" json:"script,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Output) Reset()         { *m = Output{} }
func (m *Output) String() string { return proto.CompactTextString(m) }
func (*Output) ProtoMessage()    {}
func (*Output) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{5}
}

func (m *Output) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Output.Unmarshal(m, b)
}
func (m *Output) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Output.Marshal(b, m, deterministic)
}
func (m *Output) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Output.Merge(m, src)
}
func (m *Output) XXX_Size() int {
	return xxx_messageInfo_Output.Size(m)
}
func (m *Output) XXX_DiscardUnknown() {
	xxx_messageInfo_Output.DiscardUnknown(m)
}

var xxx_messageInfo_Output proto.InternalMessageInfo

func (m *Output) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *Output) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Output) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Output) GetScript() []byte {
	if m != nil {
		return m.Script
	}
	return nil
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{6}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type SingleBytes struct {
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SingleBytes) Reset()         { *m = SingleBytes{} }
func (m *SingleBytes) String() string { return proto.CompactTextString(m) }
func (*SingleBytes) ProtoMessage()    {}
func (*SingleBytes) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{7}
}

func (m *SingleBytes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleBytes.Unmarshal(m, b)
}
func (m *SingleBytes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleBytes.Marshal(b, m, deterministic)
}
func (m *SingleBytes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleBytes.Merge(m, src)
}
func (m *SingleBytes) XXX_Size() int {
	return xxx_messageInfo_SingleBytes.Size(m)
}
func (m *SingleBytes) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleBytes.DiscardUnknown(m)
}

var xxx_messageInfo_SingleBytes proto.InternalMessageInfo

func (m *SingleBytes) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type SingleString struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SingleString) Reset()         { *m = SingleString{} }
func (m *SingleString) String() string { return proto.CompactTextString(m) }
func (*SingleString) ProtoMessage()    {}
func (*SingleString) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{8}
}

func (m *SingleString) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SingleString.Unmarshal(m, b)
}
func (m *SingleString) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SingleString.Marshal(b, m, deterministic)
}
func (m *SingleString) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SingleString.Merge(m, src)
}
func (m *SingleString) XXX_Size() int {
	return xxx_messageInfo_SingleString.Size(m)
}
func (m *SingleString) XXX_DiscardUnknown() {
	xxx_messageInfo_SingleString.DiscardUnknown(m)
}

var xxx_messageInfo_SingleString proto.InternalMessageInfo

func (m *SingleString) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type AccountAddress struct {
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountAddress) Reset()         { *m = AccountAddress{} }
func (m *AccountAddress) String() string { return proto.CompactTextString(m) }
func (*AccountAddress) ProtoMessage()    {}
func (*AccountAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{9}
}

func (m *AccountAddress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountAddress.Unmarshal(m, b)
}
func (m *AccountAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountAddress.Marshal(b, m, deterministic)
}
func (m *AccountAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountAddress.Merge(m, src)
}
func (m *AccountAddress) XXX_Size() int {
	return xxx_messageInfo_AccountAddress.Size(m)
}
func (m *AccountAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountAddress.DiscardUnknown(m)
}

var xxx_messageInfo_AccountAddress proto.InternalMessageInfo

func (m *AccountAddress) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type AccountAndRoot struct {
	Account              []byte   `protobuf:"bytes,1,opt,name=Account,proto3" json:"Account,omitempty"`
	Root                 []byte   `protobuf:"bytes,2,opt,name=Root,proto3" json:"Root,omitempty"`
	Compressed           bool     `protobuf:"varint,3,opt,name=Compressed,proto3" json:"Compressed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountAndRoot) Reset()         { *m = AccountAndRoot{} }
func (m *AccountAndRoot) String() string { return proto.CompactTextString(m) }
func (*AccountAndRoot) ProtoMessage()    {}
func (*AccountAndRoot) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{10}
}

func (m *AccountAndRoot) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountAndRoot.Unmarshal(m, b)
}
func (m *AccountAndRoot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountAndRoot.Marshal(b, m, deterministic)
}
func (m *AccountAndRoot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountAndRoot.Merge(m, src)
}
func (m *AccountAndRoot) XXX_Size() int {
	return xxx_messageInfo_AccountAndRoot.Size(m)
}
func (m *AccountAndRoot) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountAndRoot.DiscardUnknown(m)
}

var xxx_messageInfo_AccountAndRoot proto.InternalMessageInfo

func (m *AccountAndRoot) GetAccount() []byte {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *AccountAndRoot) GetRoot() []byte {
	if m != nil {
		return m.Root
	}
	return nil
}

func (m *AccountAndRoot) GetCompressed() bool {
	if m != nil {
		return m.Compressed
	}
	return false
}

type Peer struct {
	Address              *PeerAddress        `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Bestblock            *NewBlockNotice     `protobuf:"bytes,2,opt,name=bestblock,proto3" json:"bestblock,omitempty"`
	State                int32               `protobuf:"varint,3,opt,name=state,proto3" json:"state,omitempty"`
	Hidden               bool                `protobuf:"varint,4,opt,name=hidden,proto3" json:"hidden,omitempty"`
	LashCheck            int64               `protobuf:"varint,5,opt,name=lashCheck,proto3" json:"lashCheck,omitempty"`
	Selfpeer             bool                `protobuf:"varint,6,opt,name=selfpeer,proto3" json:"selfpeer,omitempty"`
	Version              string              `protobuf:"bytes,7,opt,name=version,proto3" json:"version,omitempty"`
	Certificates         []*AgentCertificate `protobuf:"bytes,8,rep,name=certificates,proto3" json:"certificates,omitempty"`
	AcceptedRole         PeerRole            `protobuf:"varint,9,opt,name=acceptedRole,proto3,enum=types.PeerRole" json:"acceptedRole,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Peer) Reset()         { *m = Peer{} }
func (m *Peer) String() string { return proto.CompactTextString(m) }
func (*Peer) ProtoMessage()    {}
func (*Peer) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{11}
}

func (m *Peer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Peer.Unmarshal(m, b)
}
func (m *Peer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Peer.Marshal(b, m, deterministic)
}
func (m *Peer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Peer.Merge(m, src)
}
func (m *Peer) XXX_Size() int {
	return xxx_messageInfo_Peer.Size(m)
}
func (m *Peer) XXX_DiscardUnknown() {
	xxx_messageInfo_Peer.DiscardUnknown(m)
}

var xxx_messageInfo_Peer proto.InternalMessageInfo

func (m *Peer) GetAddress() *PeerAddress {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *Peer) GetBestblock() *NewBlockNotice {
	if m != nil {
		return m.Bestblock
	}
	return nil
}

func (m *Peer) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *Peer) GetHidden() bool {
	if m != nil {
		return m.Hidden
	}
	return false
}

func (m *Peer) GetLashCheck() int64 {
	if m != nil {
		return m.LashCheck
	}
	return 0
}

func (m *Peer) GetSelfpeer() bool {
	if m != nil {
		return m.Selfpeer
	}
	return false
}

func (m *Peer) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *Peer) GetCertificates() []*AgentCertificate {
	if m != nil {
		return m.Certificates
	}
	return nil
}

func (m *Peer) GetAcceptedRole() PeerRole {
	if m != nil {
		return m.AcceptedRole
	}
	return PeerRole_LegacyVersion
}

type PeerList struct {
	Peers                []*Peer  `protobuf:"bytes,1,rep,name=peers,proto3" json:"peers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerList) Reset()         { *m = PeerList{} }
func (m *PeerList) String() string { return proto.CompactTextString(m) }
func (*PeerList) ProtoMessage()    {}
func (*PeerList) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{12}
}

func (m *PeerList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerList.Unmarshal(m, b)
}
func (m *PeerList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerList.Marshal(b, m, deterministic)
}
func (m *PeerList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerList.Merge(m, src)
}
func (m *PeerList) XXX_Size() int {
	return xxx_messageInfo_PeerList.Size(m)
}
func (m *PeerList) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerList.DiscardUnknown(m)
}

var xxx_messageInfo_PeerList proto.InternalMessageInfo

func (m *PeerList) GetPeers() []*Peer {
	if m != nil {
		return m.Peers
	}
	return nil
}

type ListParams struct {
	Hash                 []byte   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Height               uint64   `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Size                 uint32   `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Offset               uint32   `protobuf:"varint,4,opt,name=offset,proto3" json:"offset,omitempty"`
	Asc                  bool     `protobuf:"varint,5,opt,name=asc,proto3" json:"asc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListParams) Reset()         { *m = ListParams{} }
func (m *ListParams) String() string { return proto.CompactTextString(m) }
func (*ListParams) ProtoMessage()    {}
func (*ListParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{13}
}

func (m *ListParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListParams.Unmarshal(m, b)
}
func (m *ListParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListParams.Marshal(b, m, deterministic)
}
func (m *ListParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListParams.Merge(m, src)
}
func (m *ListParams) XXX_Size() int {
	return xxx_messageInfo_ListParams.Size(m)
}
func (m *ListParams) XXX_DiscardUnknown() {
	xxx_messageInfo_ListParams.DiscardUnknown(m)
}

var xxx_messageInfo_ListParams proto.InternalMessageInfo

func (m *ListParams) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *ListParams) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *ListParams) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *ListParams) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *ListParams) GetAsc() bool {
	if m != nil {
		return m.Asc
	}
	return false
}

type PageParams struct {
	Offset               uint32   `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Size                 uint32   `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PageParams) Reset()         { *m = PageParams{} }
func (m *PageParams) String() string { return proto.CompactTextString(m) }
func (*PageParams) ProtoMessage()    {}
func (*PageParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{14}
}

func (m *PageParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PageParams.Unmarshal(m, b)
}
func (m *PageParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PageParams.Marshal(b, m, deterministic)
}
func (m *PageParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PageParams.Merge(m, src)
}
func (m *PageParams) XXX_Size() int {
	return xxx_messageInfo_PageParams.Size(m)
}
func (m *PageParams) XXX_DiscardUnknown() {
	xxx_messageInfo_PageParams.DiscardUnknown(m)
}

var xxx_messageInfo_PageParams proto.InternalMessageInfo

func (m *PageParams) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *PageParams) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

type BlockBodyPaged struct {
	Total                uint32     `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Offset               uint32     `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Size                 uint32     `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Body                 *BlockBody `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *BlockBodyPaged) Reset()         { *m = BlockBodyPaged{} }
func (m *BlockBodyPaged) String() string { return proto.CompactTextString(m) }
func (*BlockBodyPaged) ProtoMessage()    {}
func (*BlockBodyPaged) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{15}
}

func (m *BlockBodyPaged) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockBodyPaged.Unmarshal(m, b)
}
func (m *BlockBodyPaged) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockBodyPaged.Marshal(b, m, deterministic)
}
func (m *BlockBodyPaged) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockBodyPaged.Merge(m, src)
}
func (m *BlockBodyPaged) XXX_Size() int {
	return xxx_messageInfo_BlockBodyPaged.Size(m)
}
func (m *BlockBodyPaged) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockBodyPaged.DiscardUnknown(m)
}

var xxx_messageInfo_BlockBodyPaged proto.InternalMessageInfo

func (m *BlockBodyPaged) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *BlockBodyPaged) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *BlockBodyPaged) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *BlockBodyPaged) GetBody() *BlockBody {
	if m != nil {
		return m.Body
	}
	return nil
}

type BlockBodyParams struct {
	Hashornumber         []byte      `protobuf:"bytes,1,opt,name=hashornumber,proto3" json:"hashornumber,omitempty"`
	Paging               *PageParams `protobuf:"bytes,2,opt,name=paging,proto3" json:"paging,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *BlockBodyParams) Reset()         { *m = BlockBodyParams{} }
func (m *BlockBodyParams) String() string { return proto.CompactTextString(m) }
func (*BlockBodyParams) ProtoMessage()    {}
func (*BlockBodyParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{16}
}

func (m *BlockBodyParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockBodyParams.Unmarshal(m, b)
}
func (m *BlockBodyParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockBodyParams.Marshal(b, m, deterministic)
}
func (m *BlockBodyParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockBodyParams.Merge(m, src)
}
func (m *BlockBodyParams) XXX_Size() int {
	return xxx_messageInfo_BlockBodyParams.Size(m)
}
func (m *BlockBodyParams) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockBodyParams.DiscardUnknown(m)
}

var xxx_messageInfo_BlockBodyParams proto.InternalMessageInfo

func (m *BlockBodyParams) GetHashornumber() []byte {
	if m != nil {
		return m.Hashornumber
	}
	return nil
}

func (m *BlockBodyParams) GetPaging() *PageParams {
	if m != nil {
		return m.Paging
	}
	return nil
}

type BlockHeaderList struct {
	Blocks               []*Block `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BlockHeaderList) Reset()         { *m = BlockHeaderList{} }
func (m *BlockHeaderList) String() string { return proto.CompactTextString(m) }
func (*BlockHeaderList) ProtoMessage()    {}
func (*BlockHeaderList) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{17}
}

func (m *BlockHeaderList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockHeaderList.Unmarshal(m, b)
}
func (m *BlockHeaderList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockHeaderList.Marshal(b, m, deterministic)
}
func (m *BlockHeaderList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockHeaderList.Merge(m, src)
}
func (m *BlockHeaderList) XXX_Size() int {
	return xxx_messageInfo_BlockHeaderList.Size(m)
}
func (m *BlockHeaderList) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockHeaderList.DiscardUnknown(m)
}

var xxx_messageInfo_BlockHeaderList proto.InternalMessageInfo

func (m *BlockHeaderList) GetBlocks() []*Block {
	if m != nil {
		return m.Blocks
	}
	return nil
}

type BlockMetadata struct {
	Hash                 []byte       `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Header               *BlockHeader `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	Txcount              int32        `protobuf:"varint,3,opt,name=txcount,proto3" json:"txcount,omitempty"`
	Size                 int64        `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *BlockMetadata) Reset()         { *m = BlockMetadata{} }
func (m *BlockMetadata) String() string { return proto.CompactTextString(m) }
func (*BlockMetadata) ProtoMessage()    {}
func (*BlockMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{18}
}

func (m *BlockMetadata) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockMetadata.Unmarshal(m, b)
}
func (m *BlockMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockMetadata.Marshal(b, m, deterministic)
}
func (m *BlockMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockMetadata.Merge(m, src)
}
func (m *BlockMetadata) XXX_Size() int {
	return xxx_messageInfo_BlockMetadata.Size(m)
}
func (m *BlockMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_BlockMetadata proto.InternalMessageInfo

func (m *BlockMetadata) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *BlockMetadata) GetHeader() *BlockHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *BlockMetadata) GetTxcount() int32 {
	if m != nil {
		return m.Txcount
	}
	return 0
}

func (m *BlockMetadata) GetSize() int64 {
	if m != nil {
		return m.Size
	}
	return 0
}

type BlockMetadataList struct {
	Blocks               []*BlockMetadata `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *BlockMetadataList) Reset()         { *m = BlockMetadataList{} }
func (m *BlockMetadataList) String() string { return proto.CompactTextString(m) }
func (*BlockMetadataList) ProtoMessage()    {}
func (*BlockMetadataList) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{19}
}

func (m *BlockMetadataList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BlockMetadataList.Unmarshal(m, b)
}
func (m *BlockMetadataList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BlockMetadataList.Marshal(b, m, deterministic)
}
func (m *BlockMetadataList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BlockMetadataList.Merge(m, src)
}
func (m *BlockMetadataList) XXX_Size() int {
	return xxx_messageInfo_BlockMetadataList.Size(m)
}
func (m *BlockMetadataList) XXX_DiscardUnknown() {
	xxx_messageInfo_BlockMetadataList.DiscardUnknown(m)
}

var xxx_messageInfo_BlockMetadataList proto.InternalMessageInfo

func (m *BlockMetadataList) GetBlocks() []*BlockMetadata {
	if m != nil {
		return m.Blocks
	}
	return nil
}

type CommitResult struct {
	Hash                 []byte       `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	Error                CommitStatus `protobuf:"varint,2,opt,name=error,proto3,enum=types.CommitStatus" json:"error,omitempty"`
	Detail               string       `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CommitResult) Reset()         { *m = CommitResult{} }
func (m *CommitResult) String() string { return proto.CompactTextString(m) }
func (*CommitResult) ProtoMessage()    {}
func (*CommitResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{20}
}

func (m *CommitResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitResult.Unmarshal(m, b)
}
func (m *CommitResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitResult.Marshal(b, m, deterministic)
}
func (m *CommitResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitResult.Merge(m, src)
}
func (m *CommitResult) XXX_Size() int {
	return xxx_messageInfo_CommitResult.Size(m)
}
func (m *CommitResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitResult.DiscardUnknown(m)
}

var xxx_messageInfo_CommitResult proto.InternalMessageInfo

func (m *CommitResult) GetHash() []byte {
	if m != nil {
		return m.Hash
	}
	return nil
}

func (m *CommitResult) GetError() CommitStatus {
	if m != nil {
		return m.Error
	}
	return CommitStatus_TX_OK
}

func (m *CommitResult) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

type CommitResultList struct {
	Results              []*CommitResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CommitResultList) Reset()         { *m = CommitResultList{} }
func (m *CommitResultList) String() string { return proto.CompactTextString(m) }
func (*CommitResultList) ProtoMessage()    {}
func (*CommitResultList) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{21}
}

func (m *CommitResultList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommitResultList.Unmarshal(m, b)
}
func (m *CommitResultList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommitResultList.Marshal(b, m, deterministic)
}
func (m *CommitResultList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommitResultList.Merge(m, src)
}
func (m *CommitResultList) XXX_Size() int {
	return xxx_messageInfo_CommitResultList.Size(m)
}
func (m *CommitResultList) XXX_DiscardUnknown() {
	xxx_messageInfo_CommitResultList.DiscardUnknown(m)
}

var xxx_messageInfo_CommitResultList proto.InternalMessageInfo

func (m *CommitResultList) GetResults() []*CommitResult {
	if m != nil {
		return m.Results
	}
	return nil
}

type VerifyResult struct {
	Tx                   *Tx          `protobuf:"bytes,1,opt,name=tx,proto3" json:"tx,omitempty"`
	Error                VerifyStatus `protobuf:"varint,2,opt,name=error,proto3,enum=types.VerifyStatus" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *VerifyResult) Reset()         { *m = VerifyResult{} }
func (m *VerifyResult) String() string { return proto.CompactTextString(m) }
func (*VerifyResult) ProtoMessage()    {}
func (*VerifyResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{22}
}

func (m *VerifyResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerifyResult.Unmarshal(m, b)
}
func (m *VerifyResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerifyResult.Marshal(b, m, deterministic)
}
func (m *VerifyResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerifyResult.Merge(m, src)
}
func (m *VerifyResult) XXX_Size() int {
	return xxx_messageInfo_VerifyResult.Size(m)
}
func (m *VerifyResult) XXX_DiscardUnknown() {
	xxx_messageInfo_VerifyResult.DiscardUnknown(m)
}

var xxx_messageInfo_VerifyResult proto.InternalMessageInfo

func (m *VerifyResult) GetTx() *Tx {
	if m != nil {
		return m.Tx
	}
	return nil
}

func (m *VerifyResult) GetError() VerifyStatus {
	if m != nil {
		return m.Error
	}
	return VerifyStatus_VERIFY_STATUS_OK
}

type Personal struct {
	Passphrase           string   `protobuf:"bytes,1,opt,name=passphrase,proto3" json:"passphrase,omitempty"`
	Account              *Account `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Personal) Reset()         { *m = Personal{} }
func (m *Personal) String() string { return proto.CompactTextString(m) }
func (*Personal) ProtoMessage()    {}
func (*Personal) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{23}
}

func (m *Personal) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Personal.Unmarshal(m, b)
}
func (m *Personal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Personal.Marshal(b, m, deterministic)
}
func (m *Personal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Personal.Merge(m, src)
}
func (m *Personal) XXX_Size() int {
	return xxx_messageInfo_Personal.Size(m)
}
func (m *Personal) XXX_DiscardUnknown() {
	xxx_messageInfo_Personal.DiscardUnknown(m)
}

var xxx_messageInfo_Personal proto.InternalMessageInfo

func (m *Personal) GetPassphrase() string {
	if m != nil {
		return m.Passphrase
	}
	return ""
}

func (m *Personal) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type ImportFormat struct {
	Wif                  *SingleBytes `protobuf:"bytes,1,opt,name=wif,proto3" json:"wif,omitempty"`
	Oldpass              string       `protobuf:"bytes,2,opt,name=oldpass,proto3" json:"oldpass,omitempty"`
	Newpass              string       `protobuf:"bytes,3,opt,name=newpass,proto3" json:"newpass,omitempty"`
	Keystore             *SingleBytes `protobuf:"bytes,4,opt,name=keystore,proto3" json:"keystore,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ImportFormat) Reset()         { *m = ImportFormat{} }
func (m *ImportFormat) String() string { return proto.CompactTextString(m) }
func (*ImportFormat) ProtoMessage()    {}
func (*ImportFormat) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{24}
}

func (m *ImportFormat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ImportFormat.Unmarshal(m, b)
}
func (m *ImportFormat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ImportFormat.Marshal(b, m, deterministic)
}
func (m *ImportFormat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ImportFormat.Merge(m, src)
}
func (m *ImportFormat) XXX_Size() int {
	return xxx_messageInfo_ImportFormat.Size(m)
}
func (m *ImportFormat) XXX_DiscardUnknown() {
	xxx_messageInfo_ImportFormat.DiscardUnknown(m)
}

var xxx_messageInfo_ImportFormat proto.InternalMessageInfo

func (m *ImportFormat) GetWif() *SingleBytes {
	if m != nil {
		return m.Wif
	}
	return nil
}

func (m *ImportFormat) GetOldpass() string {
	if m != nil {
		return m.Oldpass
	}
	return ""
}

func (m *ImportFormat) GetNewpass() string {
	if m != nil {
		return m.Newpass
	}
	return ""
}

func (m *ImportFormat) GetKeystore() *SingleBytes {
	if m != nil {
		return m.Keystore
	}
	return nil
}

type Staking struct {
	Amount               []byte   `protobuf:"bytes,1,opt,name=amount,proto3" json:"amount,omitempty"`
	When                 uint64   `protobuf:"varint,2,opt,name=when,proto3" json:"when,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Staking) Reset()         { *m = Staking{} }
func (m *Staking) String() string { return proto.CompactTextString(m) }
func (*Staking) ProtoMessage()    {}
func (*Staking) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{25}
}

func (m *Staking) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Staking.Unmarshal(m, b)
}
func (m *Staking) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Staking.Marshal(b, m, deterministic)
}
func (m *Staking) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Staking.Merge(m, src)
}
func (m *Staking) XXX_Size() int {
	return xxx_messageInfo_Staking.Size(m)
}
func (m *Staking) XXX_DiscardUnknown() {
	xxx_messageInfo_Staking.DiscardUnknown(m)
}

var xxx_messageInfo_Staking proto.InternalMessageInfo

func (m *Staking) GetAmount() []byte {
	if m != nil {
		return m.Amount
	}
	return nil
}

func (m *Staking) GetWhen() uint64 {
	if m != nil {
		return m.When
	}
	return 0
}

type Vote struct {
	Candidate            []byte   `protobuf:"bytes,1,opt,name=candidate,proto3" json:"candidate,omitempty"`
	Amount               []byte   `protobuf:"bytes,2,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Vote) Reset()         { *m = Vote{} }
func (m *Vote) String() string { return proto.CompactTextString(m) }
func (*Vote) ProtoMessage()    {}
func (*Vote) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{26}
}

func (m *Vote) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Vote.Unmarshal(m, b)
}
func (m *Vote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Vote.Marshal(b, m, deterministic)
}
func (m *Vote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Vote.Merge(m, src)
}
func (m *Vote) XXX_Size() int {
	return xxx_messageInfo_Vote.Size(m)
}
func (m *Vote) XXX_DiscardUnknown() {
	xxx_messageInfo_Vote.DiscardUnknown(m)
}

var xxx_messageInfo_Vote proto.InternalMessageInfo

func (m *Vote) GetCandidate() []byte {
	if m != nil {
		return m.Candidate
	}
	return nil
}

func (m *Vote) GetAmount() []byte {
	if m != nil {
		return m.Amount
	}
	return nil
}

type VoteParams struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Count                uint32   `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoteParams) Reset()         { *m = VoteParams{} }
func (m *VoteParams) String() string { return proto.CompactTextString(m) }
func (*VoteParams) ProtoMessage()    {}
func (*VoteParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{27}
}

func (m *VoteParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteParams.Unmarshal(m, b)
}
func (m *VoteParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteParams.Marshal(b, m, deterministic)
}
func (m *VoteParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteParams.Merge(m, src)
}
func (m *VoteParams) XXX_Size() int {
	return xxx_messageInfo_VoteParams.Size(m)
}
func (m *VoteParams) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteParams.DiscardUnknown(m)
}

var xxx_messageInfo_VoteParams proto.InternalMessageInfo

func (m *VoteParams) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *VoteParams) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type AccountVoteInfo struct {
	Staking              *Staking    `protobuf:"bytes,1,opt,name=staking,proto3" json:"staking,omitempty"`
	Voting               []*VoteInfo `protobuf:"bytes,2,rep,name=voting,proto3" json:"voting,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AccountVoteInfo) Reset()         { *m = AccountVoteInfo{} }
func (m *AccountVoteInfo) String() string { return proto.CompactTextString(m) }
func (*AccountVoteInfo) ProtoMessage()    {}
func (*AccountVoteInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{28}
}

func (m *AccountVoteInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountVoteInfo.Unmarshal(m, b)
}
func (m *AccountVoteInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountVoteInfo.Marshal(b, m, deterministic)
}
func (m *AccountVoteInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountVoteInfo.Merge(m, src)
}
func (m *AccountVoteInfo) XXX_Size() int {
	return xxx_messageInfo_AccountVoteInfo.Size(m)
}
func (m *AccountVoteInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountVoteInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AccountVoteInfo proto.InternalMessageInfo

func (m *AccountVoteInfo) GetStaking() *Staking {
	if m != nil {
		return m.Staking
	}
	return nil
}

func (m *AccountVoteInfo) GetVoting() []*VoteInfo {
	if m != nil {
		return m.Voting
	}
	return nil
}

type VoteInfo struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Candidates           []string `protobuf:"bytes,2,rep,name=candidates,proto3" json:"candidates,omitempty"`
	Amount               string   `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoteInfo) Reset()         { *m = VoteInfo{} }
func (m *VoteInfo) String() string { return proto.CompactTextString(m) }
func (*VoteInfo) ProtoMessage()    {}
func (*VoteInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{29}
}

func (m *VoteInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteInfo.Unmarshal(m, b)
}
func (m *VoteInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteInfo.Marshal(b, m, deterministic)
}
func (m *VoteInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteInfo.Merge(m, src)
}
func (m *VoteInfo) XXX_Size() int {
	return xxx_messageInfo_VoteInfo.Size(m)
}
func (m *VoteInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteInfo.DiscardUnknown(m)
}

var xxx_messageInfo_VoteInfo proto.InternalMessageInfo

func (m *VoteInfo) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *VoteInfo) GetCandidates() []string {
	if m != nil {
		return m.Candidates
	}
	return nil
}

func (m *VoteInfo) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

type VoteList struct {
	Votes                []*Vote  `protobuf:"bytes,1,rep,name=votes,proto3" json:"votes,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VoteList) Reset()         { *m = VoteList{} }
func (m *VoteList) String() string { return proto.CompactTextString(m) }
func (*VoteList) ProtoMessage()    {}
func (*VoteList) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{30}
}

func (m *VoteList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VoteList.Unmarshal(m, b)
}
func (m *VoteList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VoteList.Marshal(b, m, deterministic)
}
func (m *VoteList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VoteList.Merge(m, src)
}
func (m *VoteList) XXX_Size() int {
	return xxx_messageInfo_VoteList.Size(m)
}
func (m *VoteList) XXX_DiscardUnknown() {
	xxx_messageInfo_VoteList.DiscardUnknown(m)
}

var xxx_messageInfo_VoteList proto.InternalMessageInfo

func (m *VoteList) GetVotes() []*Vote {
	if m != nil {
		return m.Votes
	}
	return nil
}

func (m *VoteList) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type NodeReq struct {
	Timeout              []byte   `protobuf:"bytes,1,opt,name=timeout,proto3" json:"timeout,omitempty"`
	Component            []byte   `protobuf:"bytes,2,opt,name=component,proto3" json:"component,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeReq) Reset()         { *m = NodeReq{} }
func (m *NodeReq) String() string { return proto.CompactTextString(m) }
func (*NodeReq) ProtoMessage()    {}
func (*NodeReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{31}
}

func (m *NodeReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeReq.Unmarshal(m, b)
}
func (m *NodeReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeReq.Marshal(b, m, deterministic)
}
func (m *NodeReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeReq.Merge(m, src)
}
func (m *NodeReq) XXX_Size() int {
	return xxx_messageInfo_NodeReq.Size(m)
}
func (m *NodeReq) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeReq.DiscardUnknown(m)
}

var xxx_messageInfo_NodeReq proto.InternalMessageInfo

func (m *NodeReq) GetTimeout() []byte {
	if m != nil {
		return m.Timeout
	}
	return nil
}

func (m *NodeReq) GetComponent() []byte {
	if m != nil {
		return m.Component
	}
	return nil
}

type Name struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	BlockNo              uint64   `protobuf:"varint,2,opt,name=blockNo,proto3" json:"blockNo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Name) Reset()         { *m = Name{} }
func (m *Name) String() string { return proto.CompactTextString(m) }
func (*Name) ProtoMessage()    {}
func (*Name) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{32}
}

func (m *Name) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Name.Unmarshal(m, b)
}
func (m *Name) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Name.Marshal(b, m, deterministic)
}
func (m *Name) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Name.Merge(m, src)
}
func (m *Name) XXX_Size() int {
	return xxx_messageInfo_Name.Size(m)
}
func (m *Name) XXX_DiscardUnknown() {
	xxx_messageInfo_Name.DiscardUnknown(m)
}

var xxx_messageInfo_Name proto.InternalMessageInfo

func (m *Name) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Name) GetBlockNo() uint64 {
	if m != nil {
		return m.BlockNo
	}
	return 0
}

type NameInfo struct {
	Name                 *Name    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Owner                []byte   `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Destination          []byte   `protobuf:"bytes,3,opt,name=destination,proto3" json:"destination,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NameInfo) Reset()         { *m = NameInfo{} }
func (m *NameInfo) String() string { return proto.CompactTextString(m) }
func (*NameInfo) ProtoMessage()    {}
func (*NameInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{33}
}

func (m *NameInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NameInfo.Unmarshal(m, b)
}
func (m *NameInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NameInfo.Marshal(b, m, deterministic)
}
func (m *NameInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NameInfo.Merge(m, src)
}
func (m *NameInfo) XXX_Size() int {
	return xxx_messageInfo_NameInfo.Size(m)
}
func (m *NameInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NameInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NameInfo proto.InternalMessageInfo

func (m *NameInfo) GetName() *Name {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *NameInfo) GetOwner() []byte {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *NameInfo) GetDestination() []byte {
	if m != nil {
		return m.Destination
	}
	return nil
}

type PeersParams struct {
	NoHidden             bool     `protobuf:"varint,1,opt,name=noHidden,proto3" json:"noHidden,omitempty"`
	ShowSelf             bool     `protobuf:"varint,2,opt,name=showSelf,proto3" json:"showSelf,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeersParams) Reset()         { *m = PeersParams{} }
func (m *PeersParams) String() string { return proto.CompactTextString(m) }
func (*PeersParams) ProtoMessage()    {}
func (*PeersParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{34}
}

func (m *PeersParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeersParams.Unmarshal(m, b)
}
func (m *PeersParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeersParams.Marshal(b, m, deterministic)
}
func (m *PeersParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeersParams.Merge(m, src)
}
func (m *PeersParams) XXX_Size() int {
	return xxx_messageInfo_PeersParams.Size(m)
}
func (m *PeersParams) XXX_DiscardUnknown() {
	xxx_messageInfo_PeersParams.DiscardUnknown(m)
}

var xxx_messageInfo_PeersParams proto.InternalMessageInfo

func (m *PeersParams) GetNoHidden() bool {
	if m != nil {
		return m.NoHidden
	}
	return false
}

func (m *PeersParams) GetShowSelf() bool {
	if m != nil {
		return m.ShowSelf
	}
	return false
}

type KeyParams struct {
	Key                  []string `protobuf:"bytes,1,rep,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyParams) Reset()         { *m = KeyParams{} }
func (m *KeyParams) String() string { return proto.CompactTextString(m) }
func (*KeyParams) ProtoMessage()    {}
func (*KeyParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{35}
}

func (m *KeyParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyParams.Unmarshal(m, b)
}
func (m *KeyParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyParams.Marshal(b, m, deterministic)
}
func (m *KeyParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyParams.Merge(m, src)
}
func (m *KeyParams) XXX_Size() int {
	return xxx_messageInfo_KeyParams.Size(m)
}
func (m *KeyParams) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyParams.DiscardUnknown(m)
}

var xxx_messageInfo_KeyParams proto.InternalMessageInfo

func (m *KeyParams) GetKey() []string {
	if m != nil {
		return m.Key
	}
	return nil
}

type ServerInfo struct {
	Status               map[string]string      `protobuf:"bytes,1,rep,name=status,proto3" json:"status,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Config               map[string]*ConfigItem `protobuf:"bytes,2,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ServerInfo) Reset()         { *m = ServerInfo{} }
func (m *ServerInfo) String() string { return proto.CompactTextString(m) }
func (*ServerInfo) ProtoMessage()    {}
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{36}
}

func (m *ServerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerInfo.Unmarshal(m, b)
}
func (m *ServerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerInfo.Marshal(b, m, deterministic)
}
func (m *ServerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerInfo.Merge(m, src)
}
func (m *ServerInfo) XXX_Size() int {
	return xxx_messageInfo_ServerInfo.Size(m)
}
func (m *ServerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ServerInfo proto.InternalMessageInfo

func (m *ServerInfo) GetStatus() map[string]string {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ServerInfo) GetConfig() map[string]*ConfigItem {
	if m != nil {
		return m.Config
	}
	return nil
}

type ConfigItem struct {
	Props                map[string]string `protobuf:"bytes,2,rep,name=props,proto3" json:"props,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ConfigItem) Reset()         { *m = ConfigItem{} }
func (m *ConfigItem) String() string { return proto.CompactTextString(m) }
func (*ConfigItem) ProtoMessage()    {}
func (*ConfigItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{37}
}

func (m *ConfigItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigItem.Unmarshal(m, b)
}
func (m *ConfigItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigItem.Marshal(b, m, deterministic)
}
func (m *ConfigItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigItem.Merge(m, src)
}
func (m *ConfigItem) XXX_Size() int {
	return xxx_messageInfo_ConfigItem.Size(m)
}
func (m *ConfigItem) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigItem.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigItem proto.InternalMessageInfo

func (m *ConfigItem) GetProps() map[string]string {
	if m != nil {
		return m.Props
	}
	return nil
}

type EventList struct {
	Events               []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventList) Reset()         { *m = EventList{} }
func (m *EventList) String() string { return proto.CompactTextString(m) }
func (*EventList) ProtoMessage()    {}
func (*EventList) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{38}
}

func (m *EventList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventList.Unmarshal(m, b)
}
func (m *EventList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventList.Marshal(b, m, deterministic)
}
func (m *EventList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventList.Merge(m, src)
}
func (m *EventList) XXX_Size() int {
	return xxx_messageInfo_EventList.Size(m)
}
func (m *EventList) XXX_DiscardUnknown() {
	xxx_messageInfo_EventList.DiscardUnknown(m)
}

var xxx_messageInfo_EventList proto.InternalMessageInfo

func (m *EventList) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

// info and bps is json string
type ConsensusInfo struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Info                 string   `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	Bps                  []string `protobuf:"bytes,3,rep,name=bps,proto3" json:"bps,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConsensusInfo) Reset()         { *m = ConsensusInfo{} }
func (m *ConsensusInfo) String() string { return proto.CompactTextString(m) }
func (*ConsensusInfo) ProtoMessage()    {}
func (*ConsensusInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{39}
}

func (m *ConsensusInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConsensusInfo.Unmarshal(m, b)
}
func (m *ConsensusInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConsensusInfo.Marshal(b, m, deterministic)
}
func (m *ConsensusInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsensusInfo.Merge(m, src)
}
func (m *ConsensusInfo) XXX_Size() int {
	return xxx_messageInfo_ConsensusInfo.Size(m)
}
func (m *ConsensusInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsensusInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ConsensusInfo proto.InternalMessageInfo

func (m *ConsensusInfo) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ConsensusInfo) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func (m *ConsensusInfo) GetBps() []string {
	if m != nil {
		return m.Bps
	}
	return nil
}

type EnterpriseConfigKey struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnterpriseConfigKey) Reset()         { *m = EnterpriseConfigKey{} }
func (m *EnterpriseConfigKey) String() string { return proto.CompactTextString(m) }
func (*EnterpriseConfigKey) ProtoMessage()    {}
func (*EnterpriseConfigKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{40}
}

func (m *EnterpriseConfigKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterpriseConfigKey.Unmarshal(m, b)
}
func (m *EnterpriseConfigKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterpriseConfigKey.Marshal(b, m, deterministic)
}
func (m *EnterpriseConfigKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterpriseConfigKey.Merge(m, src)
}
func (m *EnterpriseConfigKey) XXX_Size() int {
	return xxx_messageInfo_EnterpriseConfigKey.Size(m)
}
func (m *EnterpriseConfigKey) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterpriseConfigKey.DiscardUnknown(m)
}

var xxx_messageInfo_EnterpriseConfigKey proto.InternalMessageInfo

func (m *EnterpriseConfigKey) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type EnterpriseConfig struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	On                   bool     `protobuf:"varint,2,opt,name=on,proto3" json:"on,omitempty"`
	Values               []string `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnterpriseConfig) Reset()         { *m = EnterpriseConfig{} }
func (m *EnterpriseConfig) String() string { return proto.CompactTextString(m) }
func (*EnterpriseConfig) ProtoMessage()    {}
func (*EnterpriseConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{41}
}

func (m *EnterpriseConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnterpriseConfig.Unmarshal(m, b)
}
func (m *EnterpriseConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnterpriseConfig.Marshal(b, m, deterministic)
}
func (m *EnterpriseConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnterpriseConfig.Merge(m, src)
}
func (m *EnterpriseConfig) XXX_Size() int {
	return xxx_messageInfo_EnterpriseConfig.Size(m)
}
func (m *EnterpriseConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_EnterpriseConfig.DiscardUnknown(m)
}

var xxx_messageInfo_EnterpriseConfig proto.InternalMessageInfo

func (m *EnterpriseConfig) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *EnterpriseConfig) GetOn() bool {
	if m != nil {
		return m.On
	}
	return false
}

func (m *EnterpriseConfig) GetValues() []string {
	if m != nil {
		return m.Values
	}
	return nil
}

func init() {
	proto.RegisterEnum("types.CommitStatus", CommitStatus_name, CommitStatus_value)
	proto.RegisterEnum("types.VerifyStatus", VerifyStatus_name, VerifyStatus_value)
	proto.RegisterType((*BlockchainStatus)(nil), "types.BlockchainStatus")
	proto.RegisterType((*ChainId)(nil), "types.ChainId")
	proto.RegisterType((*ChainInfo)(nil), "types.ChainInfo")
	proto.RegisterType((*ChainStats)(nil), "types.ChainStats")
	proto.RegisterType((*Input)(nil), "types.Input")
	proto.RegisterType((*Output)(nil), "types.Output")
	proto.RegisterType((*Empty)(nil), "types.Empty")
	proto.RegisterType((*SingleBytes)(nil), "types.SingleBytes")
	proto.RegisterType((*SingleString)(nil), "types.SingleString")
	proto.RegisterType((*AccountAddress)(nil), "types.AccountAddress")
	proto.RegisterType((*AccountAndRoot)(nil), "types.AccountAndRoot")
	proto.RegisterType((*Peer)(nil), "types.Peer")
	proto.RegisterType((*PeerList)(nil), "types.PeerList")
	proto.RegisterType((*ListParams)(nil), "types.ListParams")
	proto.RegisterType((*PageParams)(nil), "types.PageParams")
	proto.RegisterType((*BlockBodyPaged)(nil), "types.BlockBodyPaged")
	proto.RegisterType((*BlockBodyParams)(nil), "types.BlockBodyParams")
	proto.RegisterType((*BlockHeaderList)(nil), "types.BlockHeaderList")
	proto.RegisterType((*BlockMetadata)(nil), "types.BlockMetadata")
	proto.RegisterType((*BlockMetadataList)(nil), "types.BlockMetadataList")
	proto.RegisterType((*CommitResult)(nil), "types.CommitResult")
	proto.RegisterType((*CommitResultList)(nil), "types.CommitResultList")
	proto.RegisterType((*VerifyResult)(nil), "types.VerifyResult")
	proto.RegisterType((*Personal)(nil), "types.Personal")
	proto.RegisterType((*ImportFormat)(nil), "types.ImportFormat")
	proto.RegisterType((*Staking)(nil), "types.Staking")
	proto.RegisterType((*Vote)(nil), "types.Vote")
	proto.RegisterType((*VoteParams)(nil), "types.VoteParams")
	proto.RegisterType((*AccountVoteInfo)(nil), "types.AccountVoteInfo")
	proto.RegisterType((*VoteInfo)(nil), "types.VoteInfo")
	proto.RegisterType((*VoteList)(nil), "types.VoteList")
	proto.RegisterType((*NodeReq)(nil), "types.NodeReq")
	proto.RegisterType((*Name)(nil), "types.Name")
	proto.RegisterType((*NameInfo)(nil), "types.NameInfo")
	proto.RegisterType((*PeersParams)(nil), "types.PeersParams")
	proto.RegisterType((*KeyParams)(nil), "types.KeyParams")
	proto.RegisterType((*ServerInfo)(nil), "types.ServerInfo")
	proto.RegisterMapType((map[string]*ConfigItem)(nil), "types.ServerInfo.ConfigEntry")
	proto.RegisterMapType((map[string]string)(nil), "types.ServerInfo.StatusEntry")
	proto.RegisterType((*ConfigItem)(nil), "types.ConfigItem")
	proto.RegisterMapType((map[string]string)(nil), "types.ConfigItem.PropsEntry")
	proto.RegisterType((*EventList)(nil), "types.EventList")
	proto.RegisterType((*ConsensusInfo)(nil), "types.ConsensusInfo")
	proto.RegisterType((*EnterpriseConfigKey)(nil), "types.EnterpriseConfigKey")
	proto.RegisterType((*EnterpriseConfig)(nil), "types.EnterpriseConfig")
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_77a6da22d6a3feb1) }

var fileDescriptor_77a6da22d6a3feb1 = []byte{
	// 2624 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x19, 0xdb, 0x72, 0xdb, 0xc6,
	0x95, 0xa4, 0x44, 0x89, 0x3c, 0x24, 0x25, 0x68, 0x2d, 0xdb, 0x0a, 0x9b, 0x38, 0xea, 0xd6, 0x4d,
	0x14, 0x37, 0x51, 0x62, 0x39, 0x49, 0xd3, 0x5b, 0x52, 0x8a, 0xa1, 0x2d, 0x8e, 0x65, 0x49, 0x5d,
	0x32, 0xae, 0xd2, 0x87, 0xb2, 0x10, 0xb0, 0x24, 0x31, 0x22, 0x01, 0x04, 0x58, 0xea, 0x92, 0x99,
	0x3e, 0xf5, 0xa9, 0x7f, 0xd0, 0x99, 0xfe, 0x55, 0xdf, 0x3b, 0xed, 0xa7, 0x74, 0xf6, 0xec, 0x2e,
	0x2e, 0x14, 0xdc, 0x69, 0xfa, 0x86, 0x73, 0xbf, 0xec, 0xd9, 0xb3, 0x67, 0x17, 0x50, 0x8f, 0x42,
	0x67, 0x3f, 0x8c, 0x02, 0x11, 0x90, 0xaa, 0xb8, 0x0d, 0x79, 0xdc, 0xb6, 0x2e, 0x66, 0x81, 0x73,
	0xe9, 0x4c, 0x6d, 0xcf, 0x57, 0x84, 0x76, 0xcb, 0x76, 0x9c, 0x60, 0xe1, 0x0b, 0x0d, 0x82, 0x1f,
	0xb8, 0x5c, 0x7f, 0xd7, 0xc3, 0x83, 0x50, 0x7f, 0x36, 0xe7, 0x5c, 0x44, 0x9e, 0x56, 0xd6, 0xb6,
	0x6c, 0x1e, 0x4d, 0x82, 0x51, 0x64, 0x8f, 0xb5, 0x18, 0xfd, 0x77, 0x19, 0xac, 0xc3, 0x44, 0xf5,
	0x40, 0xd8, 0x62, 0x11, 0x93, 0xf7, 0x60, 0xf3, 0x82, 0xc7, 0x62, 0x84, 0x36, 0x47, 0x53, 0x3b,
	0x9e, 0xee, 0x94, 0x77, 0xcb, 0x7b, 0x4d, 0xd6, 0x92, 0x68, 0x64, 0x3f, 0xb2, 0xe3, 0x29, 0x79,
	0x17, 0x1a, 0xc8, 0x37, 0xe5, 0xde, 0x64, 0x2a, 0x76, 0x2a, 0xbb, 0xe5, 0xbd, 0x55, 0x06, 0x12,
	0x75, 0x84, 0x18, 0xf2, 0x53, 0xd8, 0x70, 0x02, 0x3f, 0xe6, 0x7e, 0xbc, 0x88, 0x47, 0x9e, 0x3f,
	0x0e, 0x76, 0x56, 0x76, 0xcb, 0x7b, 0x75, 0xd6, 0x4a, 0xb0, 0x7d, 0x7f, 0x1c, 0x90, 0x9f, 0x01,
	0x41, 0x3d, 0xe8, 0xc3, 0xc8, 0x73, 0x95, 0xc9, 0x55, 0x34, 0x89, 0x9e, 0x74, 0x25, 0xa1, 0xef,
	0xa2, 0xd1, 0x8f, 0x01, 0x34, 0x9f, 0xd4, 0x57, 0xdd, 0x2d, 0xef, 0x35, 0x0e, 0xac, 0x7d, 0xcc,
	0xd2, 0xbe, 0xe2, 0xf3, 0xc7, 0x01, 0xab, 0x3b, 0xe6, 0x93, 0xfe, 0xb5, 0x0c, 0xeb, 0x5a, 0x01,
	0xd9, 0x86, 0xea, 0xdc, 0x9e, 0x78, 0x0e, 0xc6, 0x53, 0x67, 0x0a, 0x20, 0x0f, 0x60, 0x2d, 0x5c,
	0x5c, 0xcc, 0x3c, 0x07, 0x43, 0xa8, 0x31, 0x0d, 0x91, 0x1d, 0x58, 0x9f, 0xdb, 0x9e, 0xef, 0x73,
	0x81, 0x7e, 0xd7, 0x98, 0x01, 0xc9, 0xdb, 0x50, 0x4f, 0x42, 0x40, 0x47, 0xeb, 0x2c, 0x45, 0x48,
	0xb9, 0x2b, 0x1e, 0xc5, 0x5e, 0xe0, 0xa3, 0x7f, 0x55, 0x66, 0x40, 0xfa, 0xaf, 0x0a, 0xd4, 0x13,
	0x27, 0xc9, 0x23, 0xa8, 0x78, 0x2e, 0xba, 0xd2, 0x38, 0xd8, 0xc8, 0x85, 0xe0, 0xb2, 0x8a, 0xe7,
	0x92, 0x36, 0xd4, 0x2e, 0xc2, 0x93, 0xc5, 0xfc, 0x82, 0x47, 0xe8, 0x59, 0x8b, 0x25, 0x30, 0xa1,
	0xd0, 0x9c, 0xdb, 0x37, 0xb8, 0x42, 0xb1, 0xf7, 0x3d, 0x47, 0x07, 0x57, 0x59, 0x0e, 0x27, 0xbd,
	0x9c, 0xdb, 0x37, 0x22, 0xb8, 0xe4, 0x7e, 0xac, 0xd3, 0x99, 0x22, 0xc8, 0x7b, 0xb0, 0x11, 0x0b,
	0xfb, 0xd2, 0xf3, 0x27, 0x73, 0xcf, 0xf7, 0xe6, 0x8b, 0x39, 0x3a, 0xdb, 0x64, 0x4b, 0x58, 0x69,
	0x49, 0x04, 0xc2, 0x9e, 0x69, 0xf4, 0xce, 0x1a, 0x72, 0xe5, 0x70, 0xd2, 0xd3, 0x89, 0x1d, 0x87,
	0x91, 0xe7, 0xf0, 0x9d, 0x75, 0xa4, 0x27, 0xb0, 0xf4, 0xc2, 0xb7, 0xe7, 0x5c, 0x11, 0x6b, 0xca,
	0x8b, 0x04, 0x41, 0x9e, 0x80, 0x85, 0x9a, 0xae, 0x02, 0xe1, 0xf9, 0x93, 0x30, 0xb8, 0xe6, 0xd1,
	0x4e, 0x1d, 0x99, 0xee, 0xe0, 0xa5, 0x27, 0x0a, 0x8c, 0xf8, 0xb5, 0x1d, 0xb9, 0x3b, 0xa0, 0x3c,
	0xc9, 0xe2, 0xe8, 0x63, 0x80, 0xae, 0x29, 0xe5, 0x58, 0xae, 0x6c, 0xc4, 0xc3, 0x20, 0x12, 0x7a,
	0xc1, 0x35, 0x44, 0x1d, 0xa8, 0xf6, 0xfd, 0x70, 0x21, 0x08, 0x81, 0xd5, 0x4c, 0x7d, 0xe3, 0xb7,
	0x5c, 0x3e, 0xdb, 0x75, 0x23, 0x1e, 0xc7, 0x3b, 0x95, 0xdd, 0x95, 0xbd, 0x26, 0x33, 0xa0, 0x2c,
	0x9f, 0x2b, 0x7b, 0xb6, 0x50, 0xd9, 0x6e, 0x32, 0x05, 0x48, 0x23, 0xb1, 0x13, 0x79, 0xa1, 0xd0,
	0x39, 0xd6, 0x10, 0x1d, 0xc3, 0xda, 0xe9, 0x42, 0x48, 0x2b, 0xdb, 0x50, 0xf5, 0x7c, 0x97, 0xdf,
	0xa0, 0x99, 0x16, 0x53, 0x40, 0xde, 0x4e, 0xf9, 0xff, 0xb7, 0xb3, 0x0e, 0xd5, 0xde, 0x3c, 0x14,
	0xb7, 0xf4, 0x27, 0xd0, 0x18, 0x78, 0xfe, 0x64, 0xc6, 0x0f, 0x6f, 0x05, 0xcf, 0x68, 0x29, 0x67,
	0xb4, 0xd0, 0xc7, 0xd0, 0x54, 0x4c, 0x03, 0x11, 0xc9, 0xa5, 0xcb, 0x71, 0xd5, 0x0d, 0xd7, 0x7b,
	0xb0, 0xd1, 0x51, 0xfd, 0xa5, 0xb3, 0xec, 0x53, 0x4e, 0xdb, 0x1f, 0x53, 0x3e, 0xdf, 0x65, 0x41,
	0x20, 0x64, 0x54, 0x1a, 0xa3, 0x39, 0x0d, 0x28, 0x73, 0x2d, 0x39, 0x74, 0xb0, 0xf8, 0x4d, 0x1e,
	0x01, 0x74, 0x83, 0x79, 0x28, 0x2d, 0x70, 0x57, 0xef, 0xb2, 0x0c, 0x86, 0xfe, 0xb3, 0x02, 0xab,
	0x67, 0x9c, 0x47, 0xe4, 0xc3, 0x34, 0x59, 0x6a, 0xc3, 0x10, 0xbd, 0x61, 0x24, 0x55, 0xfb, 0x98,
	0x26, 0xf0, 0x19, 0xd4, 0x65, 0xdf, 0xc0, 0xad, 0x80, 0xf6, 0x1a, 0x07, 0xf7, 0x35, 0xff, 0x09,
	0xbf, 0xc6, 0x0e, 0x76, 0x12, 0x08, 0xcf, 0xe1, 0x2c, 0xe5, 0x93, 0x11, 0xc6, 0xc2, 0x16, 0x2a,
	0xeb, 0x55, 0xa6, 0x00, 0x99, 0xf5, 0xa9, 0xe7, 0xba, 0xdc, 0xc7, 0xac, 0xd7, 0x98, 0x86, 0x64,
	0x59, 0xcf, 0xec, 0x78, 0xda, 0x9d, 0x72, 0xe7, 0x12, 0x77, 0xce, 0x0a, 0x4b, 0x11, 0x72, 0x43,
	0xc4, 0x7c, 0x36, 0x0e, 0x39, 0x8f, 0x70, 0xc3, 0xd4, 0x58, 0x02, 0x67, 0xdb, 0xc3, 0x3a, 0xe6,
	0xdc, 0x80, 0xe4, 0x57, 0xd0, 0x74, 0x78, 0x24, 0xbc, 0xb1, 0xe7, 0xd8, 0x82, 0xc7, 0x3b, 0xb5,
	0xdd, 0x95, 0xbd, 0xc6, 0xc1, 0x43, 0xed, 0x79, 0x67, 0xc2, 0x7d, 0xd1, 0x4d, 0xe9, 0x2c, 0xc7,
	0x4c, 0x9e, 0x41, 0xd3, 0x76, 0x1c, 0x1e, 0x0a, 0xee, 0xb2, 0x60, 0xc6, 0x71, 0x17, 0x6d, 0x1c,
	0x6c, 0x66, 0xd2, 0x24, 0xd1, 0x2c, 0xc7, 0x44, 0x3f, 0x82, 0x9a, 0xa4, 0x1c, 0x7b, 0xb1, 0x20,
	0x3f, 0x86, 0xaa, 0xf4, 0x4f, 0x26, 0x58, 0x9a, 0x6d, 0x64, 0x25, 0x15, 0x85, 0x5e, 0x01, 0x48,
	0xd6, 0x33, 0x3b, 0xb2, 0xe7, 0x71, 0xe1, 0xe6, 0x91, 0xe9, 0xca, 0x1e, 0x07, 0x1a, 0x92, 0xbc,
	0x49, 0x9f, 0x6a, 0x31, 0xfc, 0x96, 0xbc, 0xc1, 0x78, 0x1c, 0x73, 0x55, 0xd0, 0x2d, 0xa6, 0x21,
	0x62, 0xc1, 0x8a, 0x1d, 0x3b, 0x98, 0xd4, 0x1a, 0x93, 0x9f, 0xf4, 0x0b, 0x80, 0x33, 0x7b, 0xc2,
	0xb5, 0xdd, 0x54, 0xae, 0x9c, 0x93, 0x33, 0x36, 0x2a, 0xa9, 0x0d, 0x7a, 0x03, 0x1b, 0xb8, 0xdc,
	0x87, 0x81, 0x7b, 0x2b, 0x55, 0xe0, 0x19, 0x80, 0x9d, 0xc5, 0x6c, 0x46, 0x04, 0x32, 0x3a, 0x2b,
	0x85, 0x3a, 0xb3, 0x7e, 0x3f, 0x86, 0xd5, 0x8b, 0xc0, 0xbd, 0x45, 0xaf, 0xd3, 0xc3, 0x27, 0x31,
	0xc3, 0x90, 0x4a, 0xff, 0x04, 0x9b, 0x19, 0xcb, 0xe8, 0x38, 0x85, 0xa6, 0x4c, 0x52, 0x10, 0xf9,
	0xaa, 0xa9, 0xab, 0xc4, 0xe5, 0x70, 0xe4, 0x03, 0x58, 0x0b, 0xed, 0x89, 0x6c, 0xb4, 0xaa, 0x6e,
	0xb7, 0xcc, 0x32, 0x24, 0xf1, 0x33, 0xcd, 0x40, 0x7f, 0xae, 0x2d, 0x1c, 0x71, 0xdb, 0xd5, 0x6b,
	0xf8, 0x18, 0xd6, 0x54, 0xff, 0xd7, 0x8b, 0xd8, 0xcc, 0x3a, 0xc7, 0x34, 0x8d, 0xfe, 0x19, 0x5a,
	0x88, 0x78, 0xc5, 0x85, 0xed, 0xda, 0xc2, 0x2e, 0x5c, 0xc9, 0x27, 0x72, 0x25, 0xa5, 0x62, 0xed,
	0x08, 0xc9, 0xaa, 0x52, 0x26, 0x99, 0xe6, 0x90, 0x25, 0x2d, 0x6e, 0xd4, 0xa6, 0x57, 0x9b, 0xc7,
	0x80, 0x49, 0xfe, 0x56, 0x71, 0x87, 0xa8, 0x35, 0xe9, 0xc0, 0x56, 0xce, 0x3c, 0x7a, 0xfe, 0xe1,
	0x92, 0xe7, 0xdb, 0x59, 0x73, 0x86, 0x33, 0x89, 0x80, 0x43, 0xb3, 0x1b, 0xcc, 0xe7, 0x9e, 0x60,
	0x3c, 0x5e, 0xcc, 0x8a, 0xfb, 0xf8, 0x07, 0x50, 0xe5, 0x51, 0x14, 0x28, 0xff, 0x37, 0x0e, 0xee,
	0x99, 0x13, 0x16, 0xe5, 0xd4, 0xa8, 0xc3, 0x14, 0x87, 0x5c, 0x7d, 0x97, 0x0b, 0xdb, 0x9b, 0xe9,
	0x01, 0x45, 0x43, 0xb4, 0x03, 0x56, 0xd6, 0x0c, 0x3a, 0xfa, 0x11, 0xac, 0x47, 0x08, 0x19, 0x4f,
	0xf3, 0x8a, 0x15, 0x27, 0x33, 0x3c, 0x74, 0x08, 0xcd, 0xd7, 0x3c, 0xf2, 0xc6, 0xb7, 0xda, 0xd3,
	0xb7, 0xa0, 0x22, 0x6e, 0x74, 0x0f, 0xab, 0x6b, 0xc9, 0xe1, 0x0d, 0xab, 0x88, 0x9b, 0x37, 0x39,
	0xac, 0xc4, 0x73, 0x0e, 0xd3, 0xa1, 0xdc, 0xb7, 0x51, 0x1c, 0xf8, 0xf6, 0x4c, 0xf6, 0xd0, 0xd0,
	0x8e, 0xe3, 0x70, 0x1a, 0xd9, 0xb1, 0x69, 0xe3, 0x19, 0x0c, 0xd9, 0x83, 0x75, 0x3d, 0x2b, 0xea,
	0x95, 0x34, 0xb3, 0x86, 0x6e, 0xcc, 0xcc, 0x90, 0xe9, 0xdf, 0xca, 0xd0, 0xec, 0xcf, 0xe5, 0x09,
	0xf9, 0x3c, 0x88, 0xe6, 0xb6, 0x2c, 0xa7, 0x95, 0x6b, 0x6f, 0xbc, 0xd4, 0x71, 0x33, 0x67, 0x0c,
	0x93, 0x64, 0xb9, 0xfa, 0xc1, 0xcc, 0x95, 0x16, 0xd1, 0x40, 0x9d, 0x19, 0x50, 0x52, 0x7c, 0x7e,
	0x8d, 0x14, 0x95, 0x58, 0x03, 0x92, 0x7d, 0xa8, 0x5d, 0xf2, 0xdb, 0x58, 0x04, 0x11, 0xd7, 0xfb,
	0xa8, 0x48, 0x7d, 0xc2, 0x43, 0x3f, 0x83, 0xf5, 0x81, 0x1e, 0x36, 0x1e, 0xc0, 0x9a, 0x3d, 0xcf,
	0x1c, 0x30, 0x1a, 0x92, 0x35, 0x70, 0x3d, 0xe5, 0xbe, 0x6e, 0x3c, 0xf8, 0x4d, 0x7f, 0x0d, 0xab,
	0xaf, 0x03, 0x81, 0x43, 0x88, 0x63, 0xfb, 0xae, 0xe7, 0xca, 0xfe, 0xae, 0xc4, 0x52, 0x44, 0x46,
	0x63, 0x25, 0xab, 0x91, 0x1e, 0x00, 0x48, 0x69, 0xbd, 0x7b, 0x37, 0x92, 0x71, 0xad, 0x8e, 0xe3,
	0xd9, 0x36, 0x54, 0xd3, 0xac, 0xb6, 0x98, 0x02, 0xa8, 0x0b, 0x9b, 0x3a, 0xaf, 0x52, 0x14, 0xe7,
	0xbc, 0x3d, 0x58, 0x37, 0xc3, 0x53, 0x7e, 0xd8, 0xd3, 0x11, 0x31, 0x43, 0x26, 0xef, 0xc3, 0x9a,
	0x9a, 0x66, 0x70, 0xf2, 0x68, 0x24, 0xdd, 0xdb, 0xa8, 0x62, 0x9a, 0x4c, 0x19, 0xd4, 0x12, 0xf5,
	0xcb, 0x7e, 0x3d, 0x02, 0x48, 0x42, 0x53, 0x23, 0x4c, 0x9d, 0x65, 0x30, 0x99, 0x68, 0x75, 0xb1,
	0xeb, 0x68, 0x7f, 0xa3, 0x74, 0x9a, 0xb3, 0xe0, 0x2a, 0x90, 0xe2, 0xf9, 0xb3, 0x40, 0xd2, 0x99,
	0xa2, 0x68, 0xb3, 0x15, 0x63, 0x96, 0x76, 0x60, 0xfd, 0x24, 0x70, 0x39, 0xe3, 0xdf, 0x61, 0x3b,
	0xf0, 0xe6, 0x3c, 0x58, 0x24, 0x33, 0x80, 0x06, 0xd5, 0xe0, 0x3c, 0x0f, 0x03, 0x9f, 0x27, 0xc9,
	0x4e, 0x11, 0xf4, 0x53, 0x58, 0x3d, 0xb1, 0xe7, 0x5c, 0xae, 0xa4, 0x9c, 0x10, 0x75, 0x4c, 0xf8,
	0x2d, 0x75, 0x5e, 0xa8, 0x73, 0x5b, 0x2f, 0xb0, 0x01, 0xa9, 0x03, 0x35, 0x29, 0x85, 0xb9, 0x78,
	0x37, 0x23, 0x99, 0xba, 0x2d, 0xc9, 0x5a, 0xcd, 0x36, 0x54, 0x83, 0x6b, 0x5f, 0x37, 0xb5, 0x26,
	0x53, 0x00, 0xd9, 0x85, 0x86, 0xcb, 0x63, 0xe1, 0xf9, 0xb6, 0x90, 0xc7, 0xb2, 0x1a, 0xbb, 0xb2,
	0x28, 0xda, 0x83, 0x86, 0x3c, 0x08, 0x63, 0x5d, 0x0b, 0x6d, 0xa8, 0xf9, 0xc1, 0x91, 0x9a, 0x0b,
	0xca, 0xea, 0x7c, 0x37, 0x30, 0x9e, 0xfd, 0xd3, 0xe0, 0x7a, 0xc0, 0x67, 0x63, 0x7d, 0xa1, 0x48,
	0x60, 0xfa, 0x0e, 0xd4, 0x5f, 0x72, 0x73, 0x1c, 0x58, 0xb0, 0x72, 0xc9, 0x6f, 0x31, 0xc5, 0x75,
	0x26, 0x3f, 0xe9, 0x5f, 0x2a, 0x00, 0x03, 0x1e, 0x5d, 0xf1, 0x08, 0xa3, 0xf9, 0x0c, 0xd6, 0x62,
	0xdc, 0xf6, 0x7a, 0x19, 0xde, 0x31, 0x75, 0x93, 0xb0, 0xec, 0xab, 0xb6, 0xd0, 0xf3, 0x45, 0x74,
	0xcb, 0x34, 0xb3, 0x14, 0x73, 0x02, 0x7f, 0xec, 0x99, 0x2a, 0x2a, 0x10, 0xeb, 0x22, 0x5d, 0x8b,
	0x29, 0xe6, 0xf6, 0x2f, 0xa0, 0x91, 0xd1, 0x96, 0x7a, 0x57, 0xd6, 0xde, 0xa5, 0x23, 0x60, 0x25,
	0x33, 0x2a, 0xfe, 0xb2, 0xf2, 0x45, 0xb9, 0x7d, 0x0c, 0x8d, 0x8c, 0xc6, 0x02, 0xd1, 0xf7, 0xb3,
	0xa2, 0xe9, 0xa1, 0xa6, 0x84, 0xfa, 0x82, 0xcf, 0x33, 0xda, 0xe8, 0xf7, 0x72, 0x28, 0x34, 0x04,
	0x72, 0x00, 0xd5, 0x30, 0x0a, 0xc2, 0x58, 0x07, 0xf3, 0xf6, 0x1d, 0xd1, 0xfd, 0x33, 0x49, 0x56,
	0xb1, 0x28, 0xd6, 0xb6, 0x9c, 0x17, 0x12, 0xe4, 0x0f, 0x89, 0x84, 0x3e, 0x85, 0x7a, 0xef, 0x8a,
	0xfb, 0xc2, 0x9c, 0xa6, 0x5c, 0x02, 0xcb, 0xa7, 0x29, 0x72, 0x30, 0x4d, 0xa3, 0x7d, 0x68, 0x75,
	0x73, 0xf7, 0x59, 0x02, 0xab, 0x92, 0xcf, 0x94, 0xaf, 0xfc, 0x96, 0x38, 0xbc, 0xb0, 0x2a, 0x83,
	0xf8, 0x2d, 0xfd, 0xba, 0x08, 0x65, 0x67, 0xc4, 0xf5, 0xbf, 0x08, 0x63, 0xfa, 0x3e, 0xdc, 0xeb,
	0xf9, 0x82, 0x47, 0x61, 0xe4, 0xc5, 0x5c, 0x45, 0xf8, 0x92, 0x17, 0x04, 0x40, 0x8f, 0xc1, 0x5a,
	0x66, 0x2c, 0x08, 0x73, 0x03, 0x2a, 0x81, 0xaf, 0x6b, 0xb0, 0x12, 0xf8, 0x72, 0xe7, 0x63, 0xa4,
	0xc6, 0xa6, 0x86, 0x9e, 0xfc, 0xa3, 0x6c, 0x8e, 0x53, 0xfd, 0x02, 0x50, 0x87, 0xea, 0xf0, 0x7c,
	0x74, 0xfa, 0xd2, 0x2a, 0x91, 0x6d, 0xb0, 0x86, 0xe7, 0xa3, 0x93, 0xd3, 0x93, 0x6e, 0x6f, 0x34,
	0x3c, 0x3d, 0x1d, 0x1d, 0x9f, 0xfe, 0xde, 0x2a, 0x93, 0xfb, 0xb0, 0x35, 0x3c, 0x1f, 0x75, 0x8e,
	0x59, 0xaf, 0xf3, 0xf5, 0xb7, 0xa3, 0xde, 0x79, 0x7f, 0x30, 0x1c, 0x58, 0x15, 0x72, 0x0f, 0x36,
	0x87, 0xe7, 0xa3, 0xfe, 0xc9, 0xeb, 0xce, 0x71, 0xff, 0xeb, 0xd1, 0x51, 0x67, 0x70, 0x64, 0xad,
	0x2c, 0x21, 0x07, 0xfd, 0x17, 0x27, 0xd6, 0xaa, 0x56, 0x60, 0x90, 0xcf, 0x4f, 0xd9, 0xab, 0xce,
	0xd0, 0xaa, 0x92, 0x1f, 0xc1, 0x43, 0x44, 0x0f, 0xbe, 0x79, 0xfe, 0xbc, 0xdf, 0xed, 0xf7, 0x4e,
	0x86, 0xa3, 0xc3, 0xce, 0x71, 0xe7, 0xa4, 0xdb, 0xb3, 0xd6, 0xb4, 0xcc, 0x51, 0x67, 0x30, 0x1a,
	0x74, 0x5e, 0xf5, 0x94, 0x4f, 0xd6, 0x7a, 0xa2, 0x6a, 0xd8, 0x63, 0x27, 0x9d, 0xe3, 0x51, 0x8f,
	0xb1, 0x53, 0x66, 0xd5, 0x9f, 0x8c, 0xcd, 0xc1, 0xab, 0x63, 0xda, 0x06, 0xeb, 0x75, 0x8f, 0xf5,
	0x9f, 0x7f, 0x3b, 0x1a, 0x0c, 0x3b, 0xc3, 0x6f, 0x06, 0x2a, 0xbc, 0x5d, 0x78, 0x3b, 0x8f, 0x95,
	0xfe, 0x8d, 0x4e, 0x4e, 0x87, 0xa3, 0x57, 0x9d, 0x61, 0xf7, 0xc8, 0x2a, 0x93, 0x47, 0xd0, 0xce,
	0x73, 0xe4, 0xc2, 0xab, 0x1c, 0xfc, 0x9d, 0xc0, 0x66, 0x87, 0x47, 0x93, 0x80, 0x9d, 0x75, 0xe5,
	0x0e, 0x93, 0xb7, 0xda, 0xa7, 0x50, 0x97, 0xbd, 0x70, 0x80, 0x37, 0x08, 0xd3, 0xed, 0x75, 0x77,
	0x6c, 0x17, 0x1c, 0x74, 0xb4, 0x44, 0x9e, 0xc2, 0xda, 0x2b, 0x7c, 0xab, 0x21, 0xe6, 0xa6, 0xa2,
	0xc0, 0x98, 0xf1, 0xef, 0x16, 0x3c, 0x16, 0xed, 0x8d, 0x3c, 0x9a, 0x96, 0xc8, 0x67, 0x00, 0xe9,
	0xdb, 0x0d, 0x49, 0x8a, 0x53, 0xde, 0x05, 0xdb, 0x0f, 0xb3, 0xe3, 0x53, 0xe6, 0x71, 0x87, 0x96,
	0xc8, 0x27, 0xd0, 0x7c, 0xc1, 0x45, 0xfa, 0x0c, 0x91, 0x17, 0xbc, 0xf3, 0x96, 0x42, 0x4b, 0x64,
	0x5f, 0xbf, 0x5a, 0x48, 0x15, 0x4b, 0xec, 0x5b, 0x59, 0x76, 0xbc, 0x74, 0xd3, 0x12, 0xf9, 0x0a,
	0x2c, 0xb9, 0x7f, 0x32, 0x93, 0x62, 0x4c, 0x0c, 0x63, 0x7a, 0x7f, 0x68, 0x3f, 0xb8, 0x3b, 0x51,
	0x4a, 0x2a, 0x2d, 0x91, 0x43, 0xd8, 0x4a, 0x14, 0x24, 0x43, 0x6a, 0x81, 0x86, 0x9d, 0xa2, 0x21,
	0x51, 0xeb, 0x78, 0x0a, 0x9b, 0x89, 0x8e, 0x81, 0x88, 0xb8, 0x3d, 0x5f, 0x72, 0x3d, 0x37, 0x1b,
	0xd3, 0xd2, 0x27, 0x65, 0xd2, 0x81, 0x87, 0x77, 0xcc, 0x16, 0x8a, 0x16, 0x0e, 0xa7, 0xa8, 0x62,
	0x1f, 0x6a, 0x2f, 0xb8, 0xd2, 0x40, 0x0a, 0x16, 0x7a, 0xd9, 0x28, 0xf9, 0x12, 0x2c, 0xc3, 0x9f,
	0x4e, 0xe3, 0x05, 0x72, 0x6f, 0xb0, 0x48, 0xbe, 0xc2, 0xc5, 0x4c, 0x2e, 0x1a, 0xe4, 0xc1, 0xf2,
	0x6d, 0x44, 0x67, 0xea, 0xfe, 0x5d, 0xfc, 0x84, 0xbb, 0xb4, 0x44, 0xf6, 0xa0, 0xfa, 0x82, 0x8b,
	0xe1, 0x79, 0xa1, 0xd5, 0x74, 0x40, 0xa5, 0x25, 0xf2, 0x29, 0x80, 0x31, 0xf5, 0x06, 0x76, 0x2b,
	0x61, 0xef, 0xfb, 0x26, 0xc0, 0x03, 0x94, 0x62, 0xdc, 0xe1, 0x5e, 0x28, 0x0a, 0xa5, 0x4c, 0x61,
	0x6b, 0x1e, 0x5a, 0x92, 0x57, 0x8f, 0x17, 0x5c, 0x74, 0x0e, 0xfb, 0x85, 0xfc, 0x60, 0xc6, 0xd7,
	0xc3, 0xbe, 0xe2, 0x1d, 0x70, 0xdf, 0x1d, 0x9e, 0x93, 0xd4, 0xd9, 0x76, 0xd1, 0x48, 0x4e, 0xe5,
	0x66, 0x5f, 0x1b, 0x78, 0x13, 0x3f, 0xcf, 0x9b, 0x8b, 0xf1, 0x43, 0xa8, 0xa9, 0xa6, 0x51, 0xac,
	0x2f, 0x3b, 0xc9, 0x63, 0x46, 0x6a, 0xca, 0xc2, 0xf0, 0x9c, 0xb4, 0x12, 0x6e, 0x59, 0x42, 0xc9,
	0xfe, 0x5b, 0xbe, 0x3e, 0xe0, 0x6e, 0x92, 0x25, 0xa2, 0x7a, 0xc3, 0x7f, 0x2b, 0x11, 0xe4, 0xa0,
	0x25, 0xf2, 0x5b, 0x2c, 0x11, 0x84, 0x3a, 0xbe, 0x7b, 0x16, 0x05, 0xc1, 0x38, 0xe9, 0x11, 0xf9,
	0xc7, 0x97, 0xc4, 0x4f, 0x8d, 0x46, 0x5e, 0x5c, 0x83, 0x56, 0x37, 0xe2, 0x52, 0x5e, 0x3f, 0xc5,
	0xa4, 0xaf, 0x02, 0xea, 0x0e, 0xd1, 0x5e, 0xba, 0x12, 0xe0, 0xf6, 0x69, 0xc8, 0x35, 0x50, 0x70,
	0xbc, 0x54, 0xff, 0x24, 0xcf, 0xae, 0x03, 0xfb, 0x04, 0x1a, 0xc7, 0x81, 0x73, 0xf9, 0x03, 0x8c,
	0x1c, 0x40, 0xeb, 0x1b, 0x7f, 0xf6, 0xc3, 0x64, 0x3e, 0x87, 0x96, 0xba, 0xa3, 0x18, 0x19, 0x13,
	0x74, 0xf6, 0xe6, 0x52, 0x2c, 0xd7, 0xbb, 0xc9, 0xca, 0xdd, 0xb1, 0x55, 0xdc, 0x98, 0xbf, 0x84,
	0xfb, 0x39, 0xb9, 0x97, 0xfa, 0x4a, 0xf2, 0xbf, 0xca, 0x3f, 0x83, 0xd6, 0xef, 0x16, 0x3c, 0xba,
	0xed, 0x06, 0xbe, 0x88, 0x6c, 0x27, 0x6d, 0xa0, 0x88, 0x7d, 0x83, 0x50, 0x07, 0x48, 0x4e, 0x48,
	0x55, 0xcb, 0x56, 0xb6, 0x32, 0x94, 0xf8, 0x83, 0x3b, 0x28, 0xb3, 0xe8, 0x4f, 0xb1, 0xcc, 0x70,
	0x68, 0x25, 0xd9, 0xc7, 0x32, 0x3d, 0xc2, 0xb6, 0xb3, 0x2f, 0x43, 0xc9, 0x02, 0x4a, 0x91, 0xd7,
	0x38, 0xde, 0x6f, 0x65, 0x46, 0xfe, 0x25, 0x09, 0x73, 0x4b, 0xc0, 0x46, 0xbd, 0x99, 0x56, 0x89,
	0x12, 0x5c, 0x2e, 0x4d, 0xf5, 0x24, 0x97, 0x38, 0xba, 0x74, 0x39, 0x52, 0xc7, 0x98, 0xaa, 0x6f,
	0xbc, 0x02, 0xbd, 0x41, 0x7c, 0xe9, 0xca, 0x44, 0x4b, 0xe4, 0x23, 0x2c, 0xd0, 0x64, 0xf2, 0xcf,
	0xce, 0xfa, 0x89, 0xa7, 0x86, 0x8a, 0xcb, 0x8f, 0xc7, 0x01, 0x8e, 0x6e, 0xba, 0xa7, 0x9b, 0x10,
	0x9f, 0x7b, 0x33, 0xa1, 0xe6, 0xe2, 0x76, 0x6e, 0xc2, 0xc3, 0x86, 0xfe, 0x4c, 0x3d, 0x79, 0x21,
	0x22, 0x2e, 0x12, 0xb1, 0xb2, 0x22, 0x3a, 0x2d, 0x9f, 0x43, 0x4b, 0x86, 0x94, 0x4e, 0xf2, 0x86,
	0x29, 0x19, 0xfe, 0x93, 0x83, 0x33, 0x65, 0xa2, 0x25, 0xf2, 0x05, 0x6e, 0xf5, 0xfc, 0x34, 0x59,
	0x7c, 0xf2, 0xe4, 0x78, 0x68, 0x89, 0x1c, 0xc3, 0xbd, 0x17, 0x5c, 0xdc, 0x99, 0x09, 0xdb, 0x46,
	0xf8, 0xee, 0x54, 0x99, 0xb4, 0xa8, 0x65, 0x1a, 0x2d, 0x91, 0x23, 0xb8, 0xaf, 0xfc, 0x18, 0x77,
	0xa7, 0xb6, 0x3f, 0xe1, 0x67, 0x51, 0x30, 0xc1, 0x87, 0xd5, 0xa2, 0x7e, 0xf5, 0x56, 0x66, 0x22,
	0xcf, 0xb3, 0xd3, 0xd2, 0x61, 0xfd, 0x0f, 0xeb, 0xfb, 0x1f, 0x23, 0xfd, 0x62, 0x0d, 0x7f, 0x39,
	0x3d, 0xfb, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x64, 0x31, 0x6e, 0xc0, 0xde, 0x1a, 0x00, 0x00,
}
