// Code generated by mockery v1.0.0. DO NOT EDIT.
package p2p

import (
	"github.com/aergoio/aergo/message"
	"github.com/aergoio/aergo/p2p/p2pcommon"
	"github.com/stretchr/testify/mock"
)
import "github.com/aergoio/aergo/types"

// MockSyncManager is an autogenerated mock type for the MockSyncManager type
type MockSyncManager struct {
	mock.Mock
}

func (_m *MockSyncManager) HandleBlockProducedNotice(peer RemotePeer, block *types.Block) {
	_m.Called(peer, block)
}

// HandleNewBlockNotice provides a mock function with given fields: peer, hash, data
func (_m *MockSyncManager) HandleNewBlockNotice(peer RemotePeer, data *types.NewBlockNotice) {
	_m.Called(peer, data)
}

// HandleNewBlockNotice provides a mock function with given fields: peer, hash, data
func (_m *MockSyncManager) HandleGetBlockResponse(peer RemotePeer, msg p2pcommon.Message, resp *types.GetBlockResponse) {
	_m.Called(peer, msg, resp)
}

// HandleNewTxNotice provides a mock function with given fields: peer, hashes, data
func (_m *MockSyncManager) HandleNewTxNotice(peer RemotePeer, hashes []types.TxID, data *types.NewTransactionsNotice) {
	_m.Called(peer, hashes, data)
}

// HandleNewTxNotice provides a mock function with given fields: peer, hashes, data
func (_m *MockSyncManager) DoSync(peer RemotePeer, hashes []message.BlockHash, stopHash message.BlockHash) {
	_m.Called(peer, hashes, stopHash)
}
