FROM golang:1.23.10-alpine3.21
ARG GIT_TAG=master
ENV CGO_CFLAGS="-D_LARGEFILE64_SOURCE"
RUN apk update && apk add git cmake build-base m4
COPY . aergo
RUN cd aergo && make aergosvr polaris colaris aergocli aergoluac brick
