FROM debian:bookworm-slim
COPY bin/aergosvr /usr/local/bin/
COPY lib/* /usr/local/lib/
COPY conf/* /aergo/
ENV LD_LIBRARY_PATH="/usr/local/lib:${LD_LIBRARY_PATH}"
WORKDIR /aergo/
CMD ["aergosvr", "--home", "/aergo"]
EXPOSE 7845 7846 6060
