FROM debian:stable-slim
RUN apt-get update && apt-get install -y libsnappy1v5
WORKDIR /tools/
COPY bin/aergocli bin/aergoluac bin/brick /usr/local/bin/
COPY bin/brick-arglog.toml arglog.toml
COPY lib/* /usr/local/lib/
ENV LD_LIBRARY_PATH="/usr/local/lib:${LD_LIBRARY_PATH}"
CMD ["aergocli"]
