FROM golang:1.23.10-alpine3.21
ARG GIT_TAG=master
RUN apk update && apk add git cmake build-base m4 snappy-dev zlib-dev bash perl coreutils linux-headers
COPY . aergo
RUN cd aergo && make aergosvr polaris colaris aergocli aergoluac brick
