# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Complete Test

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  pull_request_target:
    types:
      - edited
  push:
    branches:
      - master
      - develop

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Install dependencies
      run: |
        sudo apt-get install -y jq m4 make cmake

    - name: Build
      run: make

    - name: Unit Tests
      run: go test -v ./...

    - name: Integration Tests
      run: |
        if [ -d "tests" ]; then
          cd tests
          ./run_tests.sh
        else
          echo "The 'tests' folder does not exist."
        fi
