# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Temporal experiments for Code Climate

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - feature/AMAIN-120-github-actions-coverage-report
      - experiment/Act*


jobs:
  pre_job:
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      coverage_flags: ${{ steps.check_ref.outputs.coverage }}
    steps:
      - id: check_ref
        if: github.event_name == 'push' && github.ref_name == 'feature/AMAIN-120-github-actions-coverage-report' && github.ref_type == 'branch'
        run: echo "coverage=-coverprofile build/c.out" >> "$GITHUB_OUTPUT"

  build_and_coverage:
    needs: pre_job
    runs-on: ubuntu-latest

    steps:
    - name: Echo status
      run: echo " event ${{github.event_name}} , on ${{github.ref_type}} ${{github.ref_name}} , coverage flags is '${{needs.pre_job.outputs.coverage_flags}}'"

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Install dependencies
      run: |
        sudo apt-get install -y jq m4 make cmake

    - name: Build
      run: make

    - name: publish code coverage
      if: github.event_name == 'push' && github.ref_name == 'master' && github.ref_type == 'branch'
      uses: paambaati/codeclimate-action@v4
      env:
        CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
      with:
        coverageCommand: go test -timeout 999s -coverprofile build/c.out  -v ./...
        prefix: github.com/aergoio/aergo
        coverageLocations: ${{github.workspace}}/build/c.out:gocov
        debug: true
    - name: no coverage
      if: github.event_name != 'push' || github.ref_name != 'master' || github.ref_type != 'branch'
      run: echo "no coverage test for other branch"
